### ISSUE TITLE
Mautic Root URL - not detected

### ISSUE THREAD

**Issue by poizenlab** [nickian/mautic-whitelabeler#1]
It cant detect the root URL -  Mautic Root URL

It does detect the absolute path though -  Where is Mautic installed? 

When root url entered in, it displays Mautic installation not found at this URL.

**Comment by nickian** [comment]
Is there a package.json file in the root of your Mautic URL? It's looking for this file to verify the domain is correct: "http://yourmautic.com/package.json".

If anyone's wondering why this validation exists, it's there to make sure the absolute URL of the new logo images that are added are correct in the new image tags (the images are uploaded to the /media/images folder). I would have used relative paths, but sometimes Mautic isn't installed in the root, so something like `<img src="/media/images/login_logo.png"/>` wouldn't work.

**Comment by redbackwebs** [comment]
Hi nickian - having the same issue .
The file package.json is not in the root of Mautic
any suggestions to create one?

**Comment by nickian** [comment]
@redbackwebs I'm not sure why your installation wouldn't have one. But if it doesn't, you can copy this file into the Mautic root: https://raw.githubusercontent.com/mautic/mautic/staging/package.json

If you do already have a package.json, make sure it (and your other Mautic files) are writable by the web server. For example:

`chown -R www-data:www-data mautic_directory`

**Comment by redbackwebs** [comment]
Thanks @nickian . Works perfectly.
This is a fantastic feature. Well done.
How will updates to Mautic effect the whitelabeling?

**Comment by nickian** [comment]
Unfortunately, If you update Mautic, it will overwrite all of the whitelabeling and you'll have to run the whitelabeling app again.

I will have to update this script each time there is an update to Mautic and make sure it's compatible. Basically, I have to make sure new versions of Mautic haven't made other changes to the files modified in this script. Otherwise, I have to create new templates for new versions each time.

So check the README.md file for the versions this is compatible with before you use it. I updated it today to work with 2.7.0.

**Comment by pckladivo** [comment]
Hi,

I have the same problem, so i downloaded the package.json. User Apache has full access to the file.
Mautic Root URL comes back green, but Where is Mautic installed? is always saying "Mautic installation not found here."

Any ideas ?

Kr,
Milos

**Comment by nickian** [comment]
@pckladivo  The script is looking for package.json to validate the domain and `/app/version.txt` to verify the path and version of Mautic. Do you have that .txt file in the app directory?

**Comment by DigitalDirector** [comment]
totally took my site offline

**Comment by nickian** [comment]
@DigitalDirector usually when my Mautic site gives me the offline error, I do this and it fixes it:

`php /path/to/mautic/app/console cache:clear`

`php /path/to/mautic/app/console cache:warmup`

or

`cd /path/to/mautic/app/cache`
`rm -r prod`
`mkdir prod`
`chown -R www-data:www-data prod`

**Comment by DigitalDirector** [comment]
worked! Thanks...

**Comment by DigitalDirector** [comment]
the color didn't change in the left sidebar

**Comment by nickian** [comment]
@DigitalDirector you probably have to clear your browser's cache.

**Comment by bazaglia** [comment]
I'm also getting:

> Mautic installation not found at this URL.

My absolute path is correctly found. I'm using official [Docker Mautic image](https://github.com/mautic/docker-mautic), which seems to doesn't include a `package.json` file in Mautic installation. Even though I created one manually and I'm able to access it in `http://localhost/package.json`, error persists. Any suggestion @nickian?

Thank you!

**Comment by nickian** [comment]
@bazaglia Hmm, I'm not sure. Can you confirm that your server allows PHP to use the file_get_contents()? Check php.ini for `allow_url_fopen = on`. Otherwise, maybe there's an issue with using localhost. Have you tried adding a virtual host with a full domain?

**Comment by bazaglia** [comment]
@nickian I checked `allow_url_fopen` in php info and it's on, as default. I also tried to use a virtual host with a full domain, but no lucky. :(

I read the URL checking is just for installations on subfolders. Is there a way I can ignore this warning and proceed anyway?

Thank you again!

**Comment by nickian** [comment]
@bazaglia You can try changing index.php on line 49 (https://github.com/nickian/mautic-whitelabeler/blob/master/index.php#L49)

Just change to `echo 1` and see what happens.

**Comment by khaoua** [comment]
Hi Nick, looking forward the new version of whitelabeler for mautic version 2.10 that just's been released ;-)

**Comment by isaipanelinha** [comment]
Absolute path to Mautic's root on your server.
**Mautic installation not found here.**

Mautic version: 2.12.1

**Comment by isaipanelinha** [comment]
I renamed the file to "package.json" and then deleted the cache. But the whitelabeler did not identify.

**Comment by nickian** [comment]
@isaipanelinha You should have package.json and package-lock.json in your root.

The absolute path to Mautic field doesn't look for package.json, it looks for /app/version.txt and checks the version number. What does that file say in your installation?

For the mautic root URL, it looks for LICENSE.txt in the root.

**Comment by isaipanelinha** [comment]
2.12.1

**Comment by nickian** [comment]
Not sure what's going on then. Maybe a permissions issue? Have you checked to see if the whitelabeler files have access through the web server user to access  the Mautic files? 

Are you using Apache? Does your Apache error log say anything? Or the browser console?

**Comment by isaipanelinha** [comment]
@nickian Thank you for your work and patience. Have you checked that users of version 2.12.1 have been able to work with whitelabeler? Did any user give you any feedback? Regards

**Comment by nickian** [comment]
No, it worked fine for me with 2.12.1. Seems to be working for this person after my last update as well: https://github.com/nickian/mautic-whitelabeler/issues/18

**Comment by isaipanelinha** [comment]
OK, @nickian ! Now, it worked for me. I downloaded the whitelabeler again, and it worked.
Thank you!

**Comment by RenerBR** [comment]
Ainda não consegui resolver o problema "Instalação Mautic não encontrada neste URL" na versão v2.12.2

**Comment by Nirind** [comment]
Hi, @nickian not working for 2.14.2 for Mautic Root URL it says
"Mautic installation not found at this URL."

**Comment by faizanrbhat** [comment]
> Hi, @nickian not working for 2.14.2 for Mautic Root URL it says
> "Mautic installation not found at this URL."

Try changing the URL to remove /app/mautic-whitelabeler
