### ISSUE TITLE
Can it be use with self hosted Mautic?

### ISSUE THREAD

**Issue by Leadspie** [nickian/mautic-whitelabeler#10]
Can it be use with self hosted Mautic?
I used it and it broke my site, I had to restore.

**Comment by nickian** [comment]
Yes, it only works with self-hosted Mautic. Can you provide more details about your hosting environment and if you received any errors in your Apache error log or in the browser console? What do you mean by "broke your site"?

**Comment by Leadspie** [comment]
Hi Nick, 

 

Thanks for Your Reply. I ran the tool, all I had to do was fix the Mautic location. Did the changes and it ran all the task successful. When I tried to open Mautic it had the site is offline because of issues message.

 

I had to restore the site. I did the logo changes manually now. Wish I had the tool working thou. Great tool. (When it works) 😉

I am sure that I must have a weird setup. It’s on Azure.

**Comment by nickian** [comment]
Oh ok. Usually if I get a site offline error for any reason, I can fix it by doing the following...

Go to your /mautic-install/app folder. Run `sudo php console cache:clear`, then `sudo php console cache:warmup`.

If that doesn't work, try doing:

    cd /mautic-install/app/cache
    sudo rm -r prod
    sudo mkdir prod
    sudo chown -R www-data:www-data prod

I'm not sure if "www-data" is the webserver user on Azure, but it is on the Ubuntu distribution I use.

**Comment by Leadspie** [comment]
Will give it a try in the future. 

Hey, while I have you here. Do you know how to avoid the Mage name reverting to Mautic when I hit the dashboard menu items?

**Comment by nickian** [comment]
The page title updating issue can be fixed on line 116 and 119 in this file:

`your-mautic/app/bundles/CoreBundle/Assets/js/1a.content.js`

Once it's updated, you have to run a command to regenerage the assets:

`php your-mautic/app/console mautic:assets:generate`
