### ISSUE TITLE
Version 3.3.1 not supported

### ISSUE THREAD

**Issue by EloneSampaio** [nickian/mautic-whitelabeler#102]
I tried to install the plugin in the new version of mautic, but I get the following error: 

The version of Mautic you are using (3.3.1) is not currently supported

**Comment by jmarcosdleon** [comment]
Hi Nikian, 

Thank you for your great plugin!

Its the same for me. I want to install it in the new Mautic version 3.3.1 but is not supported yet.

Is Mautic constantly changing the location of the color configuration files and logos?

**Comment by jsahani** [comment]
When can we except support for 3.3.1 ?

**Comment by nickian** [comment]
Just added this. Looks like nothing significant has changed, in terms of the files used in whitelabeling. That being said, I haven't thoroughly tested, so I'd recommend backing up when using the script.

**Comment by sankaravaka-ui** [comment]
Nickian, Thank you for the white Labeler. I felt very happy to see it working. Of course, it worked with 5.1.1 and the latest version is not compatible. But, I want to thank you for providing the white Labeler.
