### ISSUE TITLE
Mautic Root URL

### ISSUE THREAD

**Issue by responsiblerealist** [nickian/mautic-whitelabeler#105]
I am working on integrating mautic to an outside service and need the mautic root url of my site. Where can I find it? I tried looking into the files within cPanel but couldn't find it. Thanks

**Comment by nickian** [comment]
I'm not sure I understand your question. The "root URL" is just the address you type in to access Mautic.

**Comment by responsiblerealist** [comment]
have you tried integrating mautic with zapier or a funnel builder?

**Comment by nickian** [comment]
No, sorry. Not sure what this has to do with the whitelabeler.
