### ISSUE TITLE
Mousetrap is not defined

### ISSUE THREAD

**Issue by ankur0890** [nickian/mautic-whitelabeler#108]
I whitelabled my mautic setup using this plugin and everything works great. Able to whitelabel also with new logos and all. Console showed me all the success messages. But after clearing cache and I login all the functionalities got stopped because of javascript error 
<img width="1440" alt="Screen Shot 2021-04-29 at 3 08 42 PM" src="https://user-images.githubusercontent.com/1263424/116531461-d09b5d80-a8fc-11eb-8ea3-5301b0c14f64.png">

Tried to search it but not getting an Idea. Please help

**Comment by nickian** [comment]
What version of Mautic are you white labeling? What is your web server setup? Please provide any logs in your web server error log.

**Comment by ShareBtech** [comment]
Hey @nickian I am seeing the same problem.

I have gone ahead and tried this on Ubuntu 20.4 on Digital Ocean and AWS.
Tried with both apache and nginx web servers.
Installing latest version of Mautic 3.3.3.

**Comment by ShareBtech** [comment]
no error messages in any logs

**Comment by nickian** [comment]
I'm not sure. Not much I can do without any errors. There must be something specific on your system, like server-side caching maybe, causing this. I'm not getting these errors. I am using Ubuntu 20.04, PHP 7.4, and Apache.

**Comment by ankur0890** [comment]
@nickian  More people are facing the problem. It's reported on Mautic forum also with details. Please check it out https://forum.mautic.org/t/mautic-v3-3-3-whitelabeller-latest-no-dashboard-links-etc/19832/9

**Comment by ShareBtech** [comment]
Hey @nickian 

Would it help if i spun up a server and provided you access to it.  If you wanted you canjust provide me your public ssh key and will add you.

I have done some extensive testing and TBH I am not sure it is a problem with the plugin.  I have a feeling it might be something with php7.4 and maybe some dependency missing.  But i am not technical enough to know for sure.

I have gone ahead and done some testing, installing Mautic v3.1.0 and Whitelabelling it, all worked well, then worked my way up to 3.3.3 and I have no idea how but got it working on a test server, now trying to get it working on a real server and failing miserably.

So php files i installed were:
147  sudo apt-get install -y php7.4-{bcmath,bz2,intl,gd,mbstring,mysql,zip,common}
  148  sudo apt-get install nginx php7.4-fpm
  149  sudo apt-get install php7.4-mbstring
  150  sudo apt-get install php7.4-xml
  151  sudo apt-get install php7.4-curl
  152  sudo apt-get install php7.4-imagick php7.4-imap php7.4-gmp
  153  udo add-apt-repository ppa:ondrej/php
  154  sudo add-apt-repository ppa:ondrej/php
  155  sudo add-apt-repository ppa:ondrej/nginx
  156  sudo apt -y install software-properties-common
  157  sudo add-apt-repository ppa:ondrej/php
  158  sudo apt-get update
  197  sudo apt-get install php7.4-mbstring
  198  udo apt-get install php7.4-xml
  199  sudo apt-get install php7.4-xml
  264  sudo apt-get install php7.4-mbstring
  265  sudo apt-get install php7.4-xml
  266  sudo apt upgrade
  269  sudo apt-get install php7.4-curl
  270  sudo apt-get install php7.4-imagick php7.4-imap php7.4-gmp

**Comment by nickian** [comment]
Oh ok, hmm. Maybe it could have something to do with PHP. I will try investigating this more today. Are you running the same version of PHP with Apache as you are on the command line? The whitelabeler uses the Symfony console component to run Mautic commands to clear the cache and rebuild the frontend assets.

Are you able to go via the command line into the Mautic root and run this?:

```bash
sudo -u www-data php bin/console
```

Here is a key you can add:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzPMEKYuD6g9un18PUFIDYkoXLdhJCMfygYCWN9a21/WCCUhwKzNDHIq/zXvy0agHTXamfzBGOnNCQMzXV1pVl+y2fb9p1qqjFsQZXIwImZd6RLxVha2059HT+1N5YVzSadlcnt1yGIPa60krI6hLoxO7AXg73v803O9zwWKNIrCOmABcnUmB6YL86+kadUwj7kfuJo1hoXt0rQYbCxstAo+0Kz9QzSBe4xaSGylrpWfAMnuTpUOG6RPOypCbUvdldAbpFSMLr/hPsRF8x9uf+Gh2nwJn1AZfYWLqCGAx+5yRraLtMrc3XUxdhp+0W59gzG2R/2C8d97n3X5nTCb3FwY4p97iuwXSFiHwZxYq5MNQt4z/C1N7C9RwKk4sRtm9EraoiKJia2vgzw26qfmf0mJcPwibmKClivlwomJIFwty1du19lY8Q3h2CxSBL0QKORSuKaVwt4YfipT6YBdzmZm5ZiBpwYopwyXuenxG1zZCant+cPQCX3SCztDUjJTc=
```

**Comment by ShareBtech** [comment]
Hi Nick.

To answer your first question, yes I am able to go and run the command via command line.

I have added your key to the server.  You can access it here: 204.48.19.143.

I have done the basic apache stack installation without the above mentioned packages, I have installed v3.3.3 of Mautic and the latest release of the whitelabeler.

I have gone ahead and run the WL and the current behaviour is there. in the root directory on the server you will see a file with your mautic login details.

Please let me know once done so i can kill this image.  Feel free to write me to my email for any QA or help that i can be: mike@surge.media

**Comment by ShareBtech** [comment]
Hi Nick,  Just following up here. I understand this is done in your free time and out of the love of open source, could you give me an indication on how long I should keep this server up

**Comment by ShareBtech** [comment]
I had a developer help me look into this and he provided me this code to put into the top of the library.js file inside /mautic/media/js/

[js.txt](https://github.com/nickian/mautic-whitelabeler/files/6702961/js.txt)

**Comment by nickian** [comment]
@ShareBtech sorry, didn't see this! Thank you. I will look at this today and let you know what I find here.

**Comment by nickian** [comment]
Ok, I've poked around a bit. It appears to me that the problem is that you're installing Mautic with the `3.3.3-update.zip` file, not with the `3.3.3.zip` file. Is there a reason you used the update file?

Try installing Mautic from the correct release zip file first: https://github.com/mautic/mautic/releases/download/3.3.3/3.3.3.zip

This appears to make a difference when I tested it. If I install Mautic on my own server from `3.3.3-update.zip` file, then I whitelabel, it does produce the "Mousetrap is not defined" error.

**Comment by ShareBtech** [comment]
Hi Nick,

I think I was just pulling latest release.  Anyway have gone ahead and done so, also with the latest version of your software, and now it is not breaking, however it is not whitelabelling either.  I have left that other server up if you still would like to check it out there.....  Please let me know if you will be using it, otherwsie will go ahead and kill it

**Comment by ShareBtech** [comment]
How would i go about debugging this.  Is there a log i can see or watch to show me the changes being made ?

**Comment by ShareBtech** [comment]
Ignore my previous two comments, everything is working like magic.  My issue was after I had downgraded to 3.3.3 I forgot to chown my mautic directory.  Thank you very much for all the help and a great plugin!

**Comment by nickian** [comment]
Oh good! Glad to hear it's working. There must just be something different about that update version of the installer. I'm not sure exactly what, but I'll include that in a note on the README file.
