### ISSUE TITLE
Updating images but not CSS

### ISSUE THREAD

**Issue by brucebailey** [nickian/mautic-whitelabeler#109]
I walked through all of the steps laid out and the preview looks amazing.  But when I click the white-label button it appears to be successful but just spins on "> Updating logos and favicon ...".  I let it sit for a while and nothing else happens.  If I open a different browser, clear cache, and go to log in,  all of the images are changed (both logos and favicon), but the CSS did not update.

Any suggestions would be great.  The only requirement that we didn't meet was Apache.  We are running on a Windows server

![Screen Shot 2021-04-29 at 9 49 44 AM](https://user-images.githubusercontent.com/913250/116561571-72588580-a8d0-11eb-962d-28916358bb9e.png)

**Comment by nickian** [comment]
Sorry, I'm not sure about this. I am not at all familiar with Windows servers. Maybe someone else on here will be able to help. Can you provide any errors from the web server's error log?
