### ISSUE TITLE
Custom login logo not displaying

### ISSUE THREAD

**Issue by zietbukuel** [nickian/mautic-whitelabeler#111]
I've uploaded my login logo, yet I'm still seeing the default logo. I only see the custom logo when I visit `/s/login` but when I go to `/`, I only see the default Mautic logo.

I've cleared the caches, I've used the web UI, I've also used the CLI interface. But I always get the same results. No errors in my nginx logs as well.

I'm using the latest release of mautic-whitelabeler and Mautic 3.3.3 with PHP 7.3.28 and Nginx 1.17.3.

**Comment by nickian** [comment]
I'm not sure without any additional error messages or other information. When you refer to the caches, are you also including the nginx cache? In some environments, the nginx cache needs to be cleared (I think it's usually `/etc/nginx/cache`, but can vary). Without additional information, there is no way to help. Every hosting environment is different.

**Comment by zietbukuel** [comment]
I'm talking about the Mautic cache as Nginx does not cache by default. My environment is Laravel Forge by the way. What other info do you need?

**Comment by nickian** [comment]
I'm honestly not sure, sorry. I'm not an expert with nginx or Laravel Forge. If you're able to solve the issue, please share here.
