### ISSUE TITLE
Mautic 4.0

### ISSUE THREAD

**Issue by skacco** [nickian/mautic-whitelabeler#113]
when do will be available whitelaber for mautic 4.0?

**Comment by nickian** [comment]
I have done some preliminary testing and it should work with 4.0, but the final Mautic code has not be released yet. As soon as the final 4.0.0 release is published, I will push an update for the whitelabeler.

**Comment by zietbukuel** [comment]
Mautic 4.0 has been released a few hours ago:
https://github.com/mautic/mautic/releases/tag/4.0.0

**Comment by Hopezz** [comment]
yes it has been released, currently installed

**Comment by cayqueabreu** [comment]
I'm from Brazil, and I'm willing to help financially for this project to go to mautic 4.0, how can we do it?

**Comment by nickian** [comment]
Working on it now. It will work with 4.0.0 soon.

**Comment by cayqueabreu** [comment]
I'm trying to make a donation but I'm not getting it through paypal, is there another way?

**Comment by nickian** [comment]
Sorry for the delay. Should be working with 3.3.4 and 4.0.0 now. Still, I recommend you make a backup before using this! I only test this on my personal configurations. Thanks.

If you'd like to donate, there are a few options:

* Bitcoin: 1KZYrJX3bhj1g8QypSk6QXZSw7wuFLMqB9
* Cash App: https://cash.app/$nickian
* PayPal: https://paypal.me/nickthompson
* Venmo: https://venmo.com/nickian

Thanks!
