### ISSUE TITLE
Security access 

### ISSUE THREAD

**Issue by leonardoborlot** [nickian/mautic-whitelabeler#114]
Hi. 
How may I block non authorized access to my setup whitelabeller pannel?

**Comment by nickian** [comment]
If you are using Apache, just look at the `.htaccess` file in the root directory and uncomment (remove the #) this line:

`# deny from all`

If you're using nginx, you should be able to add something like this in the virtual host file:

```
location /mautic-whitelabeler {
    deny all;
    return 404;
}
```

Or just move the directory out of the public Mautic folder when you're done.
