### ISSUE TITLE
4.0.1 Problem images upload

### ISSUE THREAD

**Issue by leonardoborlot** [nickian/mautic-whitelabeler#119]
Hi Nick

After I confgure all informations and select my logo. I try prss Save or Whitelabel button, the script execut the json build but, cannot upload the images. 
In Console log I have this image error. 
I running the plugin in a Ubuntu 20:04 SO and Apache webserver, php 7.4.3
![uv3hO3ezrN](https://user-images.githubusercontent.com/20361821/141653998-ee17351d-394d-446b-9e27-a6ff4552da7d.png)

**Comment by nickian** [comment]
500 is a server error. Can you look at your web server's error log?

**Comment by leonardoborlot** [comment]
this error
[php7:error] [pid 121] [client 172.23.0.13:55632] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreatefrompng() in /var/www/html/whitelabeler/whitelabeler.php:451\nStack trace:\n#0 /var/www/html/whitelabeler/index.php(84): Whitelabeler->imageResize()\n#1 {main}\n  thrown in /var/www/html/whitelabeler/whitelabeler.php on line 451, referer: https://mautic4.leoborlot.com.br/whitelabeler/

**Comment by nickian** [comment]
I think you need to install the PHP GD extension. Should be something along the lines of:

`sudo apt-get install php7.0-gd`

**Comment by leonardoborlot** [comment]
Problema Solve!!
apt-get install php7.4-gd

Thanks, all right now!

**Comment by nickian** [comment]
Awesome! Glad to hear.
