### ISSUE TITLE
Mautic installation not found here - 

### ISSUE THREAD

**Issue by AutomationWay** [nickian/mautic-whitelabeler#12]
Version 2.10
cPanel latest

Confirmed that version.txt and package.json exists with proper web server permissions

After changing line 49 to echo 1 - It made some progress however it shows this error:

> Waiting for input ...
> OK
> Looking for compatible Mautic installation ...
> FOUND
> Updating CSS colors ...
> ERROR: Unable to find app.css in your Mautic installation.: 

Thanks,

**Comment by khaoua** [comment]
I have it as well, 2.9.2 works fine, but 2.10 shows 
![image](https://user-images.githubusercontent.com/25910708/30216873-b53cfbbc-94b4-11e7-94c7-eb2a53209408.png)
 mautic url, is ok, only mautic root is not found
![image](https://user-images.githubusercontent.com/25910708/30216931-e979750e-94b4-11e7-8ac5-a11dea7a5279.png)

**Comment by nickian** [comment]
Read the requirements first: "Mautic versions 2.5.0 - 2.9.2"

2.10 is just a few days new and not supported yet. I'm working on that today though.  Generally I will try to update the whitelabeler within a week or so of a new release.

**Comment by nickian** [comment]
2.10.0 should be working now if you do a git pull and try again.

**Comment by AutomationWay** [comment]
Thanks for the quick turn around, This works perfectly as expected. Great work!

**Comment by khaoua** [comment]
**@nickian** great and quick update Nick, works fine on 2.10 now, fast reactivity very much appreciated, thanks!
