### ISSUE TITLE
Error: undefined when applying whitelabel

### ISSUE THREAD

**Issue by fr500** [nickian/mautic-whitelabeler#120]
Hi

Since 4.0.2 I'm facing this:

![image](https://user-images.githubusercontent.com/1721040/142297774-bfbd18cc-b197-4fe5-a958-d8ba7f2551d5.png)

I don't see any errors in nginx logs. Just the undefinded. Anyway I can debug?

**Comment by fr500** [comment]
the cli whitelabeler works though for some reason so that's good

**Comment by fr500** [comment]
Seems to be an issue of my LEMP environment or probably a permissions thing.
When it was permissions I did get errors, so perhaps a PHP setting

**Comment by fr500** [comment]
Hmm not permissions, switched everything to www-data:www-data and 777 and nothing

**Comment by nickian** [comment]
Are you able to find any other specific errors in either the browser console or your web server's error log?

**Comment by nickian** [comment]
Also, sometimes PHP and PHP-CLI are running different versions. Make sure you have the same PHP extensions installed for both.

**Comment by fr500** [comment]
no, on my environment they are identical
on the web server I did see one permissions error, but I was able to fix that.

I just noticed nginx is not supported, but it would be nice to know why it's failing.

**Comment by nickian** [comment]
It works fine on NGINX for me. What does your NGINX error log say? Probably in `/var/log/nginx/error.log`. You can try using `tail -f /var/log/nginx/error.log` and run the whitelabeler while your terminal watches for errors in realtime.

**Comment by Getron** [comment]
Hi

The same error here

I have Apache server, php7.4 and all work fine, but this error is there, and i can't apply whitelabeler anymore.

On the v4.0 it has working, but, the last 2 versions has this problem. And i can't debug this with php logs, or web site logs, no errors there. It just stopping there, and doesn't do anything.
