### ISSUE TITLE
Not updating Logo and favicon

### ISSUE THREAD

**Issue by Hopezz** [nickian/mautic-whitelabeler#121]
> Waiting for input ...
> OK
> Looking for compatible Mautic installation ...
> FOUND
> Updating CSS colors ...
> SUCCESS
> Updating company name ...
> SUCCESS
> Updating logos and favicon ...

It keeps loading, currently using Amazon ec2 with whm cpanel

**Comment by amirzezo88** [comment]
Same issue did you found any solution
