### ISSUE TITLE
Command Line Errors

### ISSUE THREAD

**Issue by ShareBtech** [nickian/mautic-whitelabeler#123]
Hi - firstly amazing plugin if i have not already mentioned this before.

I am trying to update via cli.php however am running into issues.

My Steps:
1. First went and used the web interface to create a json file.  White labelled & saved.
2. went to terminal and checked that the json fie is there, this is my json:
`{
    "path": "\/var\/www\/ams",
    "url": "http:\/\/ams.mydomain.com\/",
    "company": "Surge.Media",
    "footer_prefix": "All Rights Reserved.",
    "footer": "Powered By Company",
    "primary": "#000000",
    "hover": "#e02b20",
    "logo_bg": "#000000",
    "sidebar_bg": "#000000",
    "sidebar_submenu_bg": "#000000",
    "sidebar_link": "#ffffff",
    "sidebar_link_hover": "#e02b20",
    "active_icon": "#e02b20",
    "sidebar_divider": "#e02b20",
    "divider_left": "50",
    "submenu_bullet_bg": "#000000",
    "submenu_bullet_shadow": "#e02b20",
    "sidebar_logo": "sm-logo-600x200-w.png",
    "sidebar_logo_width": "200",
    "sidebar_logo_margin_top": "0",
    "sidebar_logo_margin_right": "0",
    "sidebar_logo_margin_left": "0",
    "login_logo": "sm-logo-600x200-b.png",
    "login_logo_width": "300",
    "login_logo_margin_top": "20",
    "login_logo_margin_bottom": "20",
    "favicon": "surge-logo-S-500x500-blck.ico"
}
` 

3. I then went and ran the command:
`sudo -u www-data php cli.php --whitelabel --config=/var/www/ams/wl/assets/myfile.json`
and got the following errors:
`PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 846
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 852
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 858
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 863
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 868
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 873
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 878
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 883
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 888
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 893
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 898
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 903
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 908
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 913
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 918
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 923
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 928
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 933
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 938
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 943
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 948
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 953
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 958
PHP Notice:  Trying to access array offset on value of type bool in /var/www/ams/wl/whitelabeler.php on line 963
/app/version.txt file not found.
Invalid URL provided, Address timed out. Make sure it's accessible by your server's network..
Please provide a company name.
Invalid hex value provided for the primary color.
Invalid hex value provided for the hover color.
Invalid hex value provided for the sidebar logo background color.
Invalid hex value provided for the sidebar background color.
Invalid hex value provided for the sidebar submenu background color.
Invalid hex value provided for the sidebar link color.
Invalid hex value provided for the sidebar link hover color.
Invalid hex value provided for the active icon color.
Invalid hex value provided for the sidebar divider color.
Invalid hex value provided for the submenu bullet background color.
Invalid hex value provided for the submenu bullet shadow color.
Invalid sidebar logo width value provided.
Invalid sidebar_logo_margin_top value provided.
Invalid sidebar_logo_margin_right value provided.
Invalid sidebar_logo_margin_left value provided.
Invalid login logo width value provided.
Invalid login_logo_margin_top value provided.
Invalid login_logo_margin_bottom value provided.`

**Comment by nickian** [comment]
Not sure. It looks like it's just having a hard time loading the JSON file and getting `false` (bool) as the value instead of the array of values. Does the command line user you're using have correct permissions to read the file? Or have you tried using `sudo`? Does the web interface work correctly on your host?

**Comment by ShareBtech** [comment]
Hi,

1.  The web interface is working great
2. I have checked the permissions and all seems good.  Re ran chown -R www-data:www-data on the whole directory
3. Tried changing permissions to 777 even to see if that did the trick, and still getting the same errors.
4. Always running it with sudo

Not sure if it is relevant, I am running on ubuntu 20.04 with nginx server, php7.4

**Comment by nickian** [comment]
Is it the same PHP running on the command line that is running in NGINX? When you do `php -v` on the command line, does it show the same version?

**Comment by ShareBtech** [comment]
Yes they are running the same version

**Comment by ShareBtech** [comment]
I see that the first error I am getting is that it is not finding the file app/version.txt

I tried to go into /mautic/app/ and create the file there and also in the root directory of the whitelabeller and still giving me that error.

I also tried to play around a bit with the code that is looking for this in cli.php on line 260 by giving it full path as well as absolute path and still not working. (also changed persmission to 777 for this file with user www-data)

**Comment by ShareBtech** [comment]
ok I got it working.
instead of using the command: php cli.php --whitelabel --config=/path/to/specific_file.json
I just ran php cli.php --whitelabel specific_file.json and it worked!!

**Comment by nickian** [comment]
Oh ok, good! Thanks for the additional info.
