### ISSUE TITLE
ERROR: undefined on Mautic 4.0.1

### ISSUE THREAD

**Issue by diverso** [nickian/mautic-whitelabeler#124]
didn't work for me, getting another error when hitting "whitelabel" button (before had the the LICENSE.txt not found error, edited the whitelabeler.php file as mentioned here #99 )

"Waiting for input ...

OK

Looking for compatible Mautic installation ...

FOUND

Updating CSS colors ...

ERROR: undefined"

It gets stuck like this. 

Please advise

**Comment by nickian** [comment]
There is no way to advise without more information. This has something to do with your hosting environment. You will have to look at your error logs for PHP and your webserver.

**Comment by diverso** [comment]
So here's what I get in the log: "PHP Warning:  file_get_contents(https://mautic.designdiverso.com/LICENSE.txt): failed to open stream: no suitable wrapper could be found in /usr/www/users/diverso/mautic/mautic-whitelabeler/whitelabeler.php on line 96" 

Ive enabled the "allow_url_fopen" extension as well. So far I see the same error: "ERROR: undefined" within the whitelabeler. 
The required extensions are all installed unless something else is needed that I'm unaware of. 

Can you help me sort this out?
