### ISSUE TITLE
Issues updating from 4.1.1 to 4.1.2 Colors not changing

### ISSUE THREAD

**Issue by ShareBtech** [nickian/mautic-whitelabeler#127]
Hi,

I am running into issues with updating WL when moving from 4.1.1 to 4.1.2.  I have tried running from the UI and from the command line, and I see that the logos are changing without a problem, but colours are not changing.  Are there logs that i can look at to try provide more information ?

**Comment by nickian** [comment]
You can look at your web server error log. Usually something like `/var/log/apache/error.log`. Or there might be something in your browser console. Make sure permissions are set correctly on your Mautic directory.

**Comment by ShareBtech** [comment]
Thanks,  I have tried looking in the web server error logs - nothing.
Checked the console - also nothing.
Seems to be happing with only one of my instances at the moment.  Have tried everything and still colours staying the same.

Server is updated with latest patches - no idea where to go - but i guess this is a hard one to debug.

Thanks for the help and obviously for a great application!

**Comment by nickian** [comment]
Hmm, I'm not sure. Maybe there is some server-side caching going on with the styles?

**Comment by ShareBtech** [comment]
Hi,  you were spot on.  I cleared cache on servers and all looks good now.
For those that might have the same problem (I am running ubuntu) I ran the following commands:
sync; echo 1 > /proc/sys/vm/drop_caches
sync; echo 2 > /proc/sys/vm/drop_caches
sync; echo 3 > /proc/sys/vm/drop_caches

Thanks for the direction!
