### ISSUE TITLE
Whitelable issues on 4.0.1

### ISSUE THREAD

**Issue by ilsebrase** [nickian/mautic-whitelabeler#128]
Hi,

Compatible version found (4.0.1) for whitelabler, however, have issues with some components only:

1. submenu background
2. Active icon colour
3. logo background
4. general colour, primary and hover

Steps to reproduce:

1. Whitelabeler installed here: http://traceps.myicecloud.com/mautic-whitelabeler/#
2. Changes made as per requirements
3. Clicked on "Save"
4. Clicked on "whitelable"
5. Review changes on incognito window. with nr 1-4 not updated as configured.

any advice on how to troubleshoot appreciated?

**Comment by ShareBtech** [comment]
have you looked at the solution provided here: https://github.com/nickian/mautic-whitelabeler/issues/127
