### ISSUE TITLE
unable to get through url problem.

### ISSUE THREAD

**Issue by srigna** [nickian/mautic-whitelabeler#13]
Dear Nickian, 

tried all options that you have provided as common issues, but unable to get through the error - Common Issues.   I get the error Mautic installation not found at this URL.

I extracted the master.zip in the same folder where LICENSE.txt is existing.  

I can see the LICENSE.txt from my browser.   What I cannot succeed is sudo a2enmod rewrite.  It says command not found. 

where am i going wrong? 

thanks in advance.

**Comment by nickian** [comment]
Are you using Apache, or a different web server like nginx? Can you find your web server's error log and look for any specific errors?

**Comment by mannytriana** [comment]
Dear Nickian

I am having the same issue. I did make sure Apache sudo a2enmod rewrite is on. I am using the v2.10.1 version. The update process was 0 issue and also made sure permissions were 100%.

Thank You

**Comment by nickian** [comment]
What does your app/version.txt say? Make sure it's there. Is it a dev version?

What does your apache error log say?

**Comment by mannytriana** [comment]
Nickian,

Thank you for the suggestions, after looking at the Apache Logs I saw the issue.

Server related for anyone having this issue in the future : 
https://stackoverflow.com/questions/633376/apache2-not-sending-content-type-in-header

Error in Apache deals with not be able to fetch the content headers.

**Comment by anythingpixel** [comment]
So how did you fix it?

**Comment by dantearaujo** [comment]
Hi, I am using nginx and can't get through the error. When I try to browse to my license.txt it says "403 Forbidden", how can I make it accessible ?

**Comment by nickian** [comment]
I didn't develop this with nginx in mind, but I will take a look and see if I can get it to work with an nginx server.
