### ISSUE TITLE
Whitelabeler updater

### ISSUE THREAD

**Issue by PierreAmmeloot** [nickian/mautic-whitelabeler#132]
Hello @nickian, 

Thank you for your good work!

Is it possible to discuss together about the possibility of setting up a procedure for updating the code of this "plugin" in command line?

If you are available you can contact me by e-mail?

Pierre

**Comment by nickian** [comment]
I'm not sure I understand. Do you mean somehow automate creating support for new versions of Mautic?

**Comment by PierreAmmeloot** [comment]
Hello @nickian,

I mean : add a new console line to update "[mautic-whitelabeler](https://github.com/nickian/mautic-whitelabeler)" itself. :-)

Pierre

**Comment by nickian** [comment]
I'm not sure how that would be done. There is no way to predict what the Mautic team may or may not change in the core files that the whitelabeler modifies. Therefore, each time a new version of Mautic is released, we have to check to see what has updated and modify the whitelabeling template accordingly.

The best I could do would be to write up a detailed explanation of how I update the whitelabeler each time.

**Comment by nickian** [comment]
No, you don't have to do any of that. There is a `.gitingore` file in the repository that tells git to ignore the assets folder and the backups folder.

All you have to do is clone the repository. When I release a new version, you simply go into your repository and do `git pull`. Your backups and assets will not be affected. Only the whitelabeler code is updated.

**Comment by PierreAmmeloot** [comment]
Hello @nickian,

I don't have a "git repository" on my Mautic web server.
I use this command : 
```
cd www/
wget https://github.com/nickian/mautic-whitelabeler/archive/refs/tags/2.2.1.zip 
unzip 2.2.1.zip -d .
rm 2.2.1.zip
```

Pierre

**Comment by nickian** [comment]
Does your host not have git installed?

This is the easiest way to do it:

```
git clone https://github.com/nickian/mautic-whitelabeler.git
```

Then after an update has been released, just do this:

```
cd mautic-whitelabeler
git pull
git checkout 2.2.2
```

If you wanted to automate this, you could put it in a bash script `update-whitelabler.sh`:

```bash
#!/bin/bash
cd /path/to/mautic-whitelabeler
git pull
new_release=$(git describe --tags)
git checkout ${new_release}
```

Run this with:

`bash update-whitelabler.sh`
