### ISSUE TITLE
folder permission problem

### ISSUE THREAD

**Issue by smsohagbd** [nickian/mautic-whitelabeler#133]
like few days ago i tried new installation but can not access /mautic-whitelabeler/ its show 

Forbidden
You don't have permission to access this resource.

i tried 

sudo chown -R www-data:www-data /var/www/html/mautic/
sudo chmod -R 755 /var/www/html/mautic/

also chmod -R 777

**Comment by nickian** [comment]
Please read the `README.md` file in the Common Issues section:

## `.htaccess` Issue in 4.2.0+

Some changes were made to Mautic's root .htaccess file recently. If you put the whitelabeler in Mautic's root directory and try to access it, you may get a "forbidden" error as a result of the rules in this `.htaccess` file. You must either move the whitelabeler directory to another location where you can access, or simply rename the `.htaccess` file in the root temporarily, then change it back after whitelabeling.
