### ISSUE TITLE
Strange Behaviour with Dynamic Content WYSIWYG after command line whitelabel

### ISSUE THREAD

**Issue by ShareBtech** [nickian/mautic-whitelabeler#134]
Hi,

I am really not sure if this is connected, however I have experienced the following.

1. I run an update to 4.2.1 and check my instance. The reason for doing so was to get the dynamic content block showing in the email builder.
2. I went and checked and the Dynamic Content Block worked well and the wysiwyg was showing no problem.
3. I ran the command line cli.php update which worked fine and was able to whitelabel my instance, but when i go back to the dynamic content block, the wysiwyg is not there anymore.
4. This is the error i am seeing in the console:
![image](https://user-images.githubusercontent.com/59197832/164474945-21f75f65-0d29-4a25-83cf-f064d4ca98b3.png)

**Comment by nickian** [comment]
I don't see how this would be related to the whitelabeler. We don't touch the `dynamicContent.commands.js` file at all when whitelabeling. I would post in the Mautic repository or forums to try to figure this out.

Look at your web server's log and see what the details of the `400 (Bad Request)` error are.
