### ISSUE TITLE
mautic-whitelabeler on Mautic Composer

### ISSUE THREAD

**Issue by OttoSte99** [nickian/mautic-whitelabeler#135]
Hello,
is the plugin supported by Mautic Composer installation?
Regards

**Comment by nickian** [comment]
I have not tried, but I don't think it should matter. As long as Mautic is installed and the files have the correct permissions set for the web server to allow the whitelabeler to write to the files in the Mautic directory, it should work. But I would make a backup before testing it out.

**Comment by ShareBtech** [comment]
i just did a fresh install of 4.3.1 and tried to run the whitelabeller and got the following error in the console:
Waiting for input ...

> OK

> Looking for compatible Mautic installation ...

> FOUND

> Updating CSS colors ...

> ERROR: undefined: undefined

Happy to continue to debug if i am told what to do

**Comment by nickian** [comment]
Read the README.md before installing. 4.3.1 is not supported yet. Thanks for reminding me though. I will try to update this today and let you know here again once it's updated.

**Comment by ShareBtech** [comment]
Amazing Thanks @nickian .
When i run the command line cli i get the following:
`php cli.php 
PHP Fatal error:  Uncaught Error: Class 'League\CLImate\CLImate' not found in /var/www/mautic/wl/cli.php:4
Stack trace:
#0 {main}
  thrown in /var/www/ams/wl/cli.php on line 4`

**Comment by nickian** [comment]
Should be fixed now in the newest release. I think this is related to the moving of the composer file issue.
