### ISSUE TITLE
Whitelabeler for Mautic version 4.3.1

### ISSUE THREAD

**Issue by quincia** [nickian/mautic-whitelabeler#137]
Hi,
when will be released Whitelabeler for Mautic version 4.3.1?
Thank you very much!!

**Comment by nickian** [comment]
It is updated now.

**Comment by quincia** [comment]
@nickian I've updated Mautic to 4.3.1 version and Mautic Whitelabeler to the last version.
It seems to work but it doesn't change anything on the style.
I've cleared the browser cache and the mautic cache.

**Comment by JakubHelis** [comment]
@quincia @nickian  I fixed this already at one of my instances, I will provide PR later today, but I have to check if it doesn't break something on older Mautic versions (lower then 4)

**Comment by quincia** [comment]
@nickian Thanks!!
