### ISSUE TITLE
No effect on Mautic 4.3.1

### ISSUE THREAD

**Issue by quincia** [nickian/mautic-whitelabeler#138]
I've updated Mautic to 4.3.1 version and Mautic Whitelabeler to the last version.
It seems to work when I click on "whitelabel button" but it doesn't change anything on the style.
I've cleared the browser cache and the mautic cache.

**Comment by JakubHelis** [comment]
@quincia i commented on another topic 
  https://github.com/nickian/mautic-whitelabeler/issues/137#issuecomment-1147247565

**Comment by quincia** [comment]
@nickian Everything now it's OK!! Thanks!
