### ISSUE TITLE
Unable to install on 4.4.4

### ISSUE THREAD

**Issue by saidhasyim** [nickian/mautic-whitelabeler#143]
Hello, just to confirm that it does not support 4.4.4 yet, right? i installed it on 4.4.4 and i hit error launching the /mautic-whitelabeler/ url.

I will downgrade to 4.4.3 if it is not supported yet.

**Comment by nickian** [comment]
The last release should support 4.4.4. Looks like I just forgot to update the README.md file. What is the specific error you are receiving?

**Comment by saidhasyim** [comment]
I see.. I was just restoring it to 4.4.3. Let me revert back to 4.4.4. Earlier i couldn't launch the page. it just show me my custom error screen that the page is in maintenance. I will redo and capture the specfic.

**Comment by saidhasyim** [comment]
hey, i am able to access in 4.4.4 now. it was due to my htaccess. after renaming, it works.

Somehow, i cannot save any change. the loading bar just keep loading. I retried a few times to "save" and "save as". 

![Snag_2b60bb8](https://user-images.githubusercontent.com/111839161/204090659-51d21ab6-2d69-4ceb-8903-fc4214006181.png)

**Comment by saidhasyim** [comment]
hello, it works now after i whitelable and save. so, it seems that i can't save first before whitelabelling. but after whitelabelling, i can save it successfully. Thanks a lot for this.

**Comment by saidhasyim** [comment]
hmm...my icon was updated, but all the colors are not updated. even though the whitelabel process shows all ok.

Now, my mautic-whitelabeler screen just loading when i re-apply the whitelable

**Comment by saidhasyim** [comment]
I restarted my PC, and redid, and the color still not change. This time i captured the screenshot.

This in in the whitelabelling.
![Snag_2c7058b](https://user-images.githubusercontent.com/111839161/204091352-cd4e4129-ba8f-48b2-891e-73a3c9e559bc.png)


the below is in my mautic. You'd notice that the color does not change.
![Snag_2c725f4](https://user-images.githubusercontent.com/111839161/204091356-90ac6838-006b-4766-9992-01428b842ecf.png)

**Comment by saidhasyim** [comment]
all logos were changed, including login logo. Only the color is not changed.

**Comment by saidhasyim** [comment]
i retried 2 more times. still the same. the color just does not change. I deleted cache manually too.

**Comment by nickian** [comment]
You might have some server-side caching going on. I just retested the whitelabeler on 4.4.4 and the colors change for me. This has something to do with your hosting environment or browser.

You will have errors in your webserver's error log if there is a permissions issue. You can check there. Maybe PHP is having trouble writing over the CSS files because it doesn't have sufficient permissions.

**Comment by saidhasyim** [comment]
thanks a lot. Would you know which folder where it will write the css files in? I will grant 777 permission to it.
Im using a shared hosting platform and don't have access to the webserver log :( sorry.

**Comment by nickian** [comment]
The CSS files are: `/app/bundles/CoreBundle/Assets/css/app.css` and `/app/bundles/CoreBundle/Assets/css/libraries/libraries.css`.

**Comment by saidhasyim** [comment]
hey @nickian , thanks a lot for your help.
It still does not work.

I searched inside the mentioned CSS files. They were updated after i whitelabeled. In my case, i set the background-color of my sidebar to #000000 black.

![Snag_24230d8](https://user-images.githubusercontent.com/111839161/204496540-6bca3213-938a-4e9a-9a85-f0a9680fcb06.png)

But, when I viewed the webpage, the background color is not reflected. Here's the page that does not show updated background color. Also, the CSS in the browser is not updated too.
![Snag_242ad0d](https://user-images.githubusercontent.com/111839161/204496672-7f2d6b55-40b9-43e2-ba1c-3c252674ee8f.png)

**Comment by nickian** [comment]
Your webserver has probably cached the old  CSS somehow. I would look for a cache setting in your cpanel or under nginx or Apache settings. Otherwise, just open a support ticket and ask your hosting company about it.

**Comment by saidhasyim** [comment]
Thank @nickian . the support has helped me to clear cache for HTML, JS, and CSS. I will wait for 24 hours to re-verify. As of now it is still not reflected yet. (It's been >1 hour since the support staff cleared the cache. I will update you back tomorrow how it goes.

Thanks so much :)
