### ISSUE TITLE
Saving Whitelable changes "hangs"

### ISSUE THREAD

**Issue by ispmatch** [nickian/mautic-whitelabeler#144]
Hi Guys,
New latest hosting account php  versions, curl etc.
Base Mautic instance works fine

After changing various settings on the whitelabler, the system hangs.
Tried all buttons, save As, "Magic wand whitelable" button etc.

Nothing saves or changes. Tried a new MS Edge browser that I hadnt used  before in case it was a cache issue and it actually did save. No result.

Any thoughts are appreciated.
M

**Comment by nickian** [comment]
Please post errors from your web server's error log or the browser console. There is no way to know what is going on without specific errors.

**Comment by ispmatch** [comment]
Yes. Apologies @nickian 

A dump of the Chrome console below. Big red error at the end. Its been 20 years since I studied .NET. Appreciate any of your views here mate.

Objectmessage: "config.json not found in assets folder."status: 0[[Prototype]]: Object
whitelabeler.js:529 Objectmessage: "Compatible version found (4.4.5)"status: 1version: "4.4.5"[[Prototype]]: Object
whitelabeler.js:567 Objectmessage: "Mautic not found: HTTP/2 404 \r"status: 0[[Prototype]]: Object
whitelabeler.js:567 Objectmessage: "OK, Mautic found."status: 1[[Prototype]]: Object
whitelabeler.js:866 1
whitelabeler.js:914 <!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Mautic Whitelabeler</title>
	<link rel="icon" type="image/x-icon" href="images/favicon.ico" />
	<link rel="stylesheet" href="lib/bootstrap.min.css">
	<link rel='stylesheet' href="lib/spectrum/spectrum.css" />
	<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
	<link rel='stylesheet' href="lib/font-awesome-4.7.0/css/font-awesome.min.css" />
	<script src="lib/jquery-3.1.1.min.js"></script>
	<script src="lib/bootstrap.min.js"></script>
	<script src="lib/spectrum/spectrum.js"></script>
	<link rel='stylesheet' href="lib/style.css" />
</head>
<body>
	<div id="header">
		<div id="logo">
			<div id="logoimg">
	 			<img id="mautic-logo" src="images/sidebar.png" alt="" style="width:130px;margin: 10px 0 0 0;" />
			</div>
 		</div>
 		<div id="links">
 			<a href="" class="mautic-link">Primary Color</a>
 			<a href="" class="mautic-hover">Hover Color</a>
 		</div>
	</div>

	<div class="sidebar-container">
		<div class="sidebar">

		    <li class="menu-item">
		        <a href="#">
		            <span class="icon pull-left fa fa-pie-chart active-icon"></span>
		            <span class="nav-item-name">Segments</span>
		        </a>
		    </li>

		    <li class="menu-item group">
		        <a href="#">
		            <span class="icon pull-left fa fa-puzzle-piece"></span>
		            <span class="nav-item-name">Components</span>
					<span class="arrow"></span>
		        </a>

		        <ul class="nav-submenu collapse in" id="mautic_components_root_child" style="height: auto;">
		            <li class="nav-group">
		                <a href="#" data-menu-link="mautic_asset_index" id="mautic_asset_index" data-toggle="ajax"><span class="nav-item-name text">Assets</span></a>
		            </li>
		            <li class="nav-group">
		                <a href="#" data-menu-link="mautic_form_index" id="mautic_form_index" data-toggle="ajax"><span class="nav-item-name text">Forms</span></a>
		            </li>
		            <li class="nav-group">
		                <a href="#" data-menu-link="mautic_page_index" id="mautic_page_index" data-toggle="ajax"><span class="nav-item-name text">Landing Pages</span></a>
		            </li>
		            <li class="nav-group">
		                <a href="#" data-menu-link="mautic_dynamicContent_index" id="mautic_dynamicContent_index" data-toggle="ajax"><span class="nav-item-name text">Dynamic Content</span></a>
		            </li>
		        </ul>

				<li class="menu-item support">
					<h1>SUPPORT THIS PROJECT</h1>
					<p>If you find this project useful, please consider sending a small contribution. It allows me to spend more time on 
					open source software like this!</p>
					<a href="https://paypal.me/nickthompson" target="blank" class="btn btn-sm btn-support"><i class="fa fa-coffee" aria-hidden="true"></i>&nbsp;BUY ME A COFFEE</a>

					 <h1>NEED HOSTING?</h1>
					 <p>If you need fully managed web hosting compatible with Mautic and other open source software, feel free to reach out. We host and configure other open source apps like NextCloud, OnlyOffice, MatterMost, and build our own custom solutions.</p>
					 <a href="mailto:sales@creative.link?subject=Mautic%20Hosting" target="blank" class="btn btn-sm btn-support"><i class="fa fa-commenting" aria-hidden="true"></i>&nbsp;CONTACT</a>
		        </li>
		    </li>

		</div>
	</div>

	<div class="whitelabeler">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<div id="options">
						<div class="row">
							<div class="col-md-12">
								<h2>Mautic Whitelabeler</h2>
								<p>See the <a href="https://github.com/nickian/mautic-whitelabeler" target="_blank" class="mautic-link">GitHub page</a> for more information and instructions.</p>
								<p>Don't use this without making a backup of your Mautic files first!</p>
								<hr/>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<form method="post" enctype="multipart/form-data">
									<div id="basic">
										<div class="form-group">
											<label for="mautic-path">Where is Mautic installed?</label><br/>
											<small>Absolute path to Mautic's root on your server.</small>
											<div class="field-container">
												<input type="text" class="form-control" id="mautic-path" name="mautic_path">
												<span id="path-loading">
													<i class="fa fa-spinner fa-spin"></i>
												</span>
											</div>
											<small class="path-success"></small>
											<small class="path-fail"></small>
										</div>
										<div class="form-group">
											<label for="mautic-url">Mautic URL</label><br/>
											<div class="field-container">
												<input type="text" class="form-control" name="mautic_url" id="mautic-url" placeholder="">
												<span id="url-loading">
													<i class="fa fa-s
whitelabeler.js:915 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at Object.success (whitelabeler.js:915:47)
    at i (jquery-3.1.1.min.js:2:27983)
    at Object.fireWith [as resolveWith] (jquery-3.1.1.min.js:2:28749)
    at A (jquery-3.1.1.min.js:4:14203)
    at XMLHttpRequest.<anonymous> (jquery-3.1.1.min.js:4:16491)

**Comment by nickian** [comment]
Not sure that anything helpful is in the console there. Look for errors in your webserver's error log (Apache or nginx, etc.).

**Comment by ispmatch** [comment]
Cheers Nick,

I owe you a beer.
If you are ever downunder / Australia, be sure to ping me :-)

Mark


<https://mailerplex.com?utm_source=gmail&utm_medium=signature&utm_campaign=signature1>
Tracked
via MailerPlex Email Tracker
<https://mailerplex.com?utm_source=gmail&utm_medium=signature&utm_campaign=signature1>

**Comment by ispmatch** [comment]
Hey Nick,

Interesting response from my hosting company.

They confirm they have no problem making mods and saving. No err logs either they state.
It might be some weird global cache issue. I actually didnt check loggin is as admin, but when I went to the whitelable today, the hosting companies changes were there. BUT they did not display in the main login screen and dashboard. 
Some screen shots also of a perecived error, but the new logos and an extra test (copy of) have been uploaded to the whitelable asset folders.



See below Hosting Company response

![whitelable logo issue 1](https://user-images.githubusercontent.com/10086480/213849354-8456fc7b-e6a9-4b14-a74b-082070a61fbe.png)
![whitelable logo issue 2](https://user-images.githubusercontent.com/10086480/213849356-342361ef-44c0-4db2-b252-f183605d1944.png)
.

Hi Mark,

I just tested this again and am able to make changes to the color as well as other settings.

As for the logo upload, I tried using a SVG file which is stuck in the spinning logo but if I use a PNG file, I am able to upload it successfully. I left my changes there so you can see that it can be done.

If it still doesn't work for you, I suggest trying a different image file, maybe a smaller image size, a JPG or PNG file, etc. You may also want to try it with your browser's Private or Incognito Mode to rule out any browser extensions problem.

I am also not seeing any error logs at all, which indicate that there's no server level issues or even code issues at play here. You will see a file with the name error_log if there are any errors.

Unfortunately we will not be able to provide much support beyond this as it is an application level matter which we are unfamiliar with.

**Comment by nickian** [comment]
I'm not sure what's going on there. If there are no errors, maybe it's just caching or a CDN/network caching thing. I don't think SVG files will work currently, but I can see if that can be changed in the future.

**Comment by ispmatch** [comment]
right.

Not really after SVG's but some may want that.
I just dont get this as to why?
Flushed caches and browser caches too ???

Cheers,
M


<https://mailerplex.com?utm_source=gmail&utm_medium=signature&utm_campaign=signature1>
Tracked
via MailerPlex Email Tracker
<https://mailerplex.com?utm_source=gmail&utm_medium=signature&utm_campaign=signature1>

**Comment by nickian** [comment]
Unfortunately, I have no idea. I didn't build this with shared hosting environments or caching in mind. I use it on VPS machines that I have full control over. The only suggestion I can think of is to try testing it out in a different environment and see if you get different results.
