### ISSUE TITLE
Favicon.ico not found

### ISSUE THREAD

**Issue by iam-GOXT** [nickian/mautic-whitelabeler#146]
![Screenshot 2023-02-25 075712](https://user-images.githubusercontent.com/58105850/221343447-c9a72de4-64f6-4f90-8db2-f3cd86918d28.png)
Mautic not found. Make sure favicon.ico exists in the domain root, check for errors in your server error log.

the error i keep getting, i have tried every means possible,

**Comment by nickian** [comment]
Not sure if you eventually resolved this. Please feel free to still comment here and add any error messages that you see in your web server log. Without specific errors, it's hard to say what is going on.
