### ISSUE TITLE
Forbidden You don't have permission to access this resource.

### ISSUE THREAD

**Issue by pwnoobz** [nickian/mautic-whitelabeler#147]
Hey, I just downloaded your git content inside the main folder of Mautic. When trying to access that folder trough the browser, I'm getting:

```
Forbidden
You don't have permission to access this resource.

Apache/2.4.54 (Debian) Server at *******.com Port 443 
```

while images from mautic-whitelabeler folder open fine.

**Comment by nickian** [comment]
I believe this is because some of the .htaccess rules changed a while back. You can either move the whitelabeler to a different directory/domain to access and make sure it still have write access to the mautic files, or use the command line interface, or leave it where it is and temporarily rename the .htaccess file to some thing else, use the whitelabeler, then rename the .htaccess back to its original name.

**Comment by pwnoobz** [comment]
Thank you for your answer. This was the first thing I tried. Unfortunately, I'll suspend my experiments since I decided to use another alternative method.

**Comment by nickian** [comment]
Sorry, not sure how to help with this. I'm closing the issue for now, but feel free to comment again if you discover a solution.

**Comment by jpgiron1981** [comment]
Hello, i have the same problem, it was permission on the files for mautic. 

For security reason all the mautic files and folders are block to be execute.

This is on the .htacess file and in the read/write/execute permision on the servers for each folder. 

You need to look your .htacess or your htaccess.conf and change the parameter

when i install, i have this error, look on the log server and show me something about authz_core_module error.

I look on the conf file and found this in the end of the file


  ```
# Apache 2.4+
  <IfModule authz_core_module>
      # Deny access via HTTP requests to all PHP files.
      <FilesMatch "\.php$">
          Require all denied
      </FilesMatch>


      # Deny access via HTTP requests to composer files.
      <FilesMatch "^(composer\.json|composer\.lock)$">
         Require all denied
      </FilesMatch>

      # Except those allowed below.
      <If "%{REQUEST_URI} =~ m#^/(index|index_dev|upgrade/upgrade)\.php#">
          Require all granted
      </If>
  </IfModule>

  # Fallback for Apache < 2.4
  <IfModule !authz_core_module>
      # Deny access via HTTP requests to all PHP files.
      <FilesMatch "\.php$">
         Order deny,allow
         Deny from all
      </FilesMatch>

      # Deny access via HTTP requests to composer files
      <FilesMatch "^(composer\.json|composer\.lock)$">
          Order deny,allow
          Deny from all
      </FilesMatch>

      # Except those allowed below.
      <If "%{REQUEST_URI} =~ m#^/(index|index_dev|upgrade/upgrade)\.php#">
          Order allow,deny
          Allow from all
      </If>
  </IfModule>
</Directory>
```

and put # on all lines, restart the server and can install the whitelabeler. After this, get back, uncomment this for get the security for my installation.

Also remember change the file permision to 777 for all whitelabeler and get back it.
