### ISSUE TITLE
Mautic Root URL won't accept a https address

### ISSUE THREAD

**Issue by eisenbuerger** [nickian/mautic-whitelabeler#15]
Mautic is secured by ssl. If I type in the current domain, starting with https, the error message "Mautic installation not found at this URL." comes up. By using http instead of https, everything works. 

But the whitelabeler updates the files with the unsecured logo paths.

It would be great to make this work.

Thanks!
Sebastian

**Comment by nickian** [comment]
This was probably the same issue as in this thread: https://github.com/nickian/mautic-whitelabeler/issues/22
