### ISSUE TITLE
LeftPanel logo changing itself

### ISSUE THREAD

**Issue by tadeusz-bronczyk-droptica** [nickian/mautic-whitelabeler#150]
**Description:**
In the Mautic v4.4.9 and the newest mautic-whitelabeler the logo changes after whitelabeling to the choosen one, but while using the Mautic instance through the admin panel the left panel logo is changing back to the Mautic one.

**Setps to reconstruct:**
1. Change the left panel (sidebar) logo in mautic-whitelabeler and whitelabel your Mautic instance
2. Log in to the Mautic admin panel
3. Go to the Account settings
4. Change the language for user and save settings
5. Refresh the page by using CTRL+F5

**Additional insight:**
From some debugging it seems that Mautic is mixing up the view files for left panel (_app/bundles/CoreBundle/Views/LeftPanel_) and uses both files **_index.html.twig_**, **_index.html.php_** interchangeably. Mautic-whitelabeler seems to only change the php version of template.

**Proposed solution:**
Make mautic-whitelabeler change both files.

**Comment by nickian** [comment]
I can't replicate this issue. Changing the language doesn't seem to have any affect on the sidebar logo for me.

**Comment by nickian** [comment]
I was finally able to replicate this in version 4 of Mautic. However, now version 5+ is only using twig templates, so it should no longer be an issue moving forward.
