### ISSUE TITLE
Mautic 4.4.10

### ISSUE THREAD

**Issue by quincia** [nickian/mautic-whitelabeler#151]
When have you planned to release the new compatible version of mautic whitelabeler?
Best regards.

**Comment by zietbukuel** [comment]
I'm also waiting for this. Not trying to be pushy but do you have an ETA maybe? Thanks.

**Comment by nickian** [comment]
Sorry for the delay. I will update by tomorrow.

**Comment by Ahriman** [comment]
Thanks :)

**Comment by nickian** [comment]
It is updated now.
