### ISSUE TITLE
5.0.0 suuport?

### ISSUE THREAD

**Issue by radicalidol** [nickian/mautic-whitelabeler#152]
hi, 
do you have an update in works for the 5.x versions of mautic?

**Comment by nickian** [comment]
I haven't looked at it yet. I'm not sure if, or how much, the code base is going to change in that release. I will try to take a look at the beta this weekend to see what it's looking like. Thanks.

**Comment by nickian** [comment]
Sorry for the delay. Should work now with all of the newest versions.
