### ISSUE TITLE
Image Sizing Issue

### ISSUE THREAD

**Issue by KaivalyaDeshpande** [nickian/mautic-whitelabeler#153]
This error is coming. I tried different sizes. https://ibb.co/SwYC7tB

Please kindly add instructions on how to resolve this.

Thanks.

**Comment by KaivalyaDeshpande** [comment]
Undefined error is coming when I try to click on whitelabel button. https://prnt.sc/vAjMOgQ9cyQ8

**Comment by nickian** [comment]
I'm not sure what is happening there. Can you provide errors from the web server's error log? Or also see if there are specific errors in the browser console?
