### ISSUE TITLE
Local server shows 403 error. 

### ISSUE THREAD

**Issue by mthakur5** [nickian/mautic-whitelabeler#154]
i have give permission 644 & tried 755 with mautic-whitelabeler folder in docker root folder. .i don't understand what i should do here for use this? 

<img width="1512" alt="Screenshot 2023-12-20 at 2 04 36 PM" src="https://github.com/nickian/mautic-whitelabeler/assets/138131563/3bfc1c87-ce32-42dc-bfbb-604e83c424fe">

**Comment by mthakur5** [comment]
i have given all permission. 

> Sorry, I'm not sure. This looks like a permissions issue or another environment issue not specific to the whitelabeler. I don't use the Docker version.

**Comment by nickian** [comment]
Does the Apache error log say anything?

**Comment by djimatr** [comment]
I get the same error or similiar error with permissions: apache and virtualmin - mautic runs fine: I have granted the correct permissions and even tried 777  but after navigating to whitelabeler directory I get this in the apache log:
 [Tue May 14 14:52:45.424498 2024] [authz_core:error] [pid 16720:tid 16753] [client xx.xx.xx.xx:53406] AH01630: client denied by server configuration: /home/campaign/public_html/mautic-whitelabeler/index.php

**Comment by djimatr** [comment]
In my case what I had to do was rename the mautic root .htaccess file to .htaccess_off to get the white-labeler to work. Once you are done with the whitelabel configuration I had to rename the root .htaccess back to its original name. Everything worked. I also tried commenting out the mautic-whitelabeler .htaccess but that just created an error.

**Comment by nickian** [comment]
Oh good, thanks for sharing.

**Comment by khangdo17** [comment]
> In my case what I had to do was rename the mautic root .htaccess file to .htaccess_off to get the white-labeler to work. Once I was done with the whitelabel configuration I had to rename the root .htaccess back to its original name. Everything worked. I also tried commenting out the mautic-whitelabeler .htaccess but that just created an error.

hello sir , i have the same problem with you, but when i change the .htaccess file to edit the whitelabeler, it doesn't let me to approve the change and the mautic url say. Can you help me how you whitelabelp it, thank you so much.
![image](https://github.com/user-attachments/assets/a1d74051-3a29-4946-af5d-e23768f3a20d)

![mautic](https://github.com/user-attachments/assets/f2942653-7d98-401a-9eaf-684eb8329b3a)
