### ISSUE TITLE
Support for Mautic 5.x?

### ISSUE THREAD

**Issue by juancholasso** [nickian/mautic-whitelabeler#155]
When could the module be used for mautic version 5.x?

**Comment by TonyBogdanov** [comment]
+1

**Comment by pm-pmaas** [comment]
> In progress. They switched to using Twig templates in all of the views so this will take a little more work and code refactoring than normal. I'll see if I can make more progress today.

Hi, when u expect to have this ready for Mautic 5 ?

**Comment by BeneBlack90** [comment]
+1

**Comment by nickian** [comment]
Sorry for the delay. Should work now with all of the newest versions.
