### ISSUE TITLE
Support for Mautic 4.4.11

### ISSUE THREAD

**Issue by matbcvo** [nickian/mautic-whitelabeler#156]
Mautic has released version 4.4.11. Would be nice to add support for that.

https://github.com/mautic/mautic/releases/tag/4.4.11

**Comment by nickian** [comment]
I will wrap this into the update for 5.0+. For now, if you need 4.4.11 support, just copy the `4.4.10` directory in the templates folder and name the copy `4.4.11` and it should work.

**Comment by nickian** [comment]
Sorry for the delay. Should work now with all of the newest versions.
