### ISSUE TITLE
> ERROR: Could not update company name. See console for errors

### ISSUE THREAD

**Issue by willdotcom** [nickian/mautic-whitelabeler#158]
**Describe the bug**
On clean Mautic i have the error :

```
> SUCCESS
> Updating company name ...
> ERROR: Could not update company name. See console for error.
```

**Mautic Version**
Mautic Version:  (4.4.11)

**Web Server Error Logs**
Console:
```
{
    "status": 0,
    "message": [
        "Unable to find Mautic file: /app/bundles/CoreBundle/Resources/views/Default/base.html.php",
        "Unable to find Mautic file: /app/bundles/CoreBundle/Resources/views/Default/head.html.php",
        "Unable to find Mautic file: /app/bundles/UserBundle/Resources/views/Security/base.html.php"
    ]
}
```

**Hosting Environtment**
Hostin cPanel, work on all anothers mautic.

**Comment by shishirjinu** [comment]
Hi i have found this error,
client denied by server configuration: /home/arissaint/public_html/domain/mautic-whitelabeler/index.php
In cpanel. How to fix it.

**Comment by nickian** [comment]
Sorry, I'm not sure. That's a server configuration issue specific to your hosting environment, not a bug with the whitelabeler. I would submit an issue to your hosting provider with the errors you find in your logs.
