### ISSUE TITLE
404 Not Found on Mautic 5.0.4

### ISSUE THREAD

**Issue by uniqsoft-net** [nickian/mautic-whitelabeler#161]
**Describe the bug**
I have downloaded latest mautic-whitelabeler and upload to root of path/mymautic.url/public_html/mautic-whitelabeler-master
When I access from browser, it shows Error 404. I renamed the .htaccess and it still shows 404 error
I uploaded to other path and I can access whitelabeler but it show error 
/home/mymautic.url/public_html/app/version.txt file not found.
When I saw the root folder of mymautic, I didn't find /app folder instead I found /docroot/app
but in this folder there is no version.txt file

**Mautic Version**
5.0.4

**Hosting Environtment**
CyberPanel on Ubuntu 22.04 and Mautic on php 8.1

**Comment by uniqsoft-net** [comment]
Really need a solution, if anybody have the solution then please respond :)

**Comment by nickian** [comment]
Can you make sure that the web server user has access to the Mautic root folder? I'm not sure what CyberPanel uses, but normally for me it would be `www-data`, so I could have the whitelabeler in its own directory with it's own subdomain that has access to the separate Mautic files. I would do `sudo chown -R www-data:www-data /path/to/mautic`

**Comment by uniqsoft-net** [comment]
Hello Nick,
Thanks for your reply. CyberPanel create new unique web server user for each website. I have found it and done

sudo chown -R autonoc7857:autoc7857 /path/to/mautic

but I have still same 404 not found, I have chnage read/write permission to 0777 recursively but still same error. If you have any more tips, I will oblige :)

**Comment by nickian** [comment]
Ok, I'm not sure. But I will try testing Cyberpanel today because I'm curious about it anyway. I'll let you know what I find out testing it.

**Comment by nickian** [comment]
Well, I tried testing CyberPanel and ran into way too many issues. Couldn't get rewrite rules to work like a normal Apache server. I couldn't get it to work using separate websites, and I couldn't get the whitelabeler to fully work on the command line either. 

CyberPanel has a lot of moving parts and seems very opinionated/sensitive about permissions and configurations. I tend to avoid overly-complicated systems like this in favor of simple and more flexible servers, where I have full control and know the ins and outs of what's running.

Maybe someone else on here is more experienced with CyberPanel. It would probably require completely separate instructions and maybe even a fork to change some of the whitelabeler code to accomadate CyberPanel nuances. Sorry I couldn't help more.

**Comment by uniqsoft-net** [comment]
Thanks for your help and feedback about cyberpanel but I have done lot of mautic installation with automatic MAUTIC install feature of CyberPanel and it works like a charm and done lot of mautic whaite label with your whitelabeler with old mautic 4 versions.
This issue occurs with MAUTIC 5+ version. You have to look into something for version 5+ :)

**Comment by nickian** [comment]
Some things have changed with 5+, but it hasn't affected normal installs on my servers. In the previous versions, were you putting the `mautic-whitelabeler` directory inside of the Mautic directory? So you would go to yourmauticsite.com/mautic-whitelabeler to use it?

**Comment by nickian** [comment]
Ok, actually I got it to work now!

You have to put the whitelabeler directory in the `public_html/docroot` folder. 

Then temporarily disable the `public_html/docroot/.htaccess` file. (I just removed the `.` and called it `htaccess`). 

Then go to `http://yourmautic.com/mautic-whitelabeler`, run the whitelabeling.

Then set the htaccess file back to `.htaccess`.

I had to fully reboot the server in order to clear the server's cache before the color changes would show up FYI.

**Comment by uniqsoft-net** [comment]
Thanks Nick, its work like a charm :)
