### ISSUE TITLE
version.txt file not found.

### ISSUE THREAD

**Issue by pm-pmaas** [nickian/mautic-whitelabeler#163]
**Describe the bug**
Since i have updated to mautic 5.1.0 ( by a composer setup ) im not abble to run the whitelabeler again. I got the following error:

/data/web/mautic/app/version.txt file not found.

My mautic installation is in /data/web/mautic
The whitelabeler is in /data/web/mautic/pub

The version files are availble:

app@map:~/mautic/public/app$ ls -all
total 88
drwxrwxr-x  9 app app  4096 Jun 14 07:11 .
drwxr-xr-x  8 app app  4096 Jun 14 07:22 ..
-rw-rw-r--  1 app app   224 Jun 12 13:45 AppCache.php
-rw-rw-r--  1 app app 13354 Jun 12 13:45 AppKernel.php
-rw-rw-r--  1 app app  1168 Jun 12 13:45 AppTestKernel.php
drwxrwxr-x  9 app app  4096 Jun 12 13:45 assets
drwxrwxr-x 30 app app  4096 Jun 12 13:45 bundles
drwxrwxr-x  3 app app  4096 Jun 12 13:45 codingstandards
-rw-rw-r--  1 app app  6438 Jun 12 13:45 composer.json
drwxrwxr-x  2 app app  4096 Jun 12 13:45 config
-rw-rw-r--  1 app app  1483 Jun 12 13:45 console-application.php
drwxrwxr-x  3 app app  4096 Jun 12 13:45 .github
-rw-rw-r--  1 app app    13 Jun 12 13:45 .htaccess
drwxrwxr-x  4 app app  4096 Jun 12 13:45 middlewares
drwxrwxr-x  2 app app  4096 Jun 12 13:45 migrations
-rw-rw-r--  1 app app  2867 Jun 12 13:45 phpunit.xml.dist
-rw-rw-r--  1 app app   322 Jun 12 13:45 README.md
-rw-rw-r--  1 app app   358 Jun 14 07:11 release_metadata.json
app@map:~/mautic/public/app$

**Mautic Version**
5.1.0

**Web Server Error Logs**
Make sure to include any errors from your web server log. Without specific error messages, there's no way to diagnose the problem.

**To Reproduce**
1. Go to whitelabeler
2. See error /data/web/mautic/app/version.txt file not found.

**Hosting Environtment**
Ubuntu

**Screenshots**

**Comment by nickian** [comment]
5.1.0 is not a supported version yet. Hoping to dig into this version here soon though.
