### ISSUE TITLE
Whitelabeler Doesnt Work with Mautic v5.1.0

### ISSUE THREAD

**Issue by hazelmountain** [nickian/mautic-whitelabeler#166]
**Describe the bug**
The Plugin doesnt work with the newest Version of Mautic

**Mautic Version**
v5.1.0

**Comment by Hollowiman** [comment]
Is there any estimate when 5.1.0 support will come?

**Comment by nickian** [comment]
Sorry for the long delay. This has been updated.

**Comment by Hollowiman** [comment]
Works, and changes logo's and favicon in 5.1.0, but cant make those colors changed? ( CSS )

**Comment by nickian** [comment]
Try regenerating assets in the Maurice CLI console after whitelabeling. Or just run `composer install` in the Mautic root. Then clear your browser cache too.
