### ISSUE TITLE
Divider color is not changing.

### ISSUE THREAD

**Issue by hayathasan** [nickian/mautic-whitelabeler#167]
**Describe the bug**
After runing `bin/console mautic:assets:generate` everythings updated except the divider color, no mater how many times I clear the cache it simply doesn't update 

**Mautic Version**
What version of Mautic are you running? 
5.1.1

**Web Server Error Logs**
Make sure to include any errors from your web server log. Without specific error messages, there's no way to diagnose the problem.

**To Reproduce**

**Hosting Environtment**
Describe the server you're running Mautic on (e.g., Ubuntu, Docker, what version of PHP, etc.)

**Screenshots**
![image](https://github.com/user-attachments/assets/0852747d-a950-456f-8eab-a2f2e1cb09f7)

**Comment by nickian** [comment]
Thank you for pointing this out. You're correct. There was a missing value for the new CSS in versions 5+. Should be all fixed now.
