### ISSUE TITLE
tool use impossible

### ISSUE THREAD

**Issue by louridi-brahim** [nickian/mautic-whitelabeler#168]
Hello,
I retrieved the zip of "mautic-whitelabeler" and I copied the folder to the root of my host but it does not work, I have this error:
This page does not work
cdp.bldigitalagency.fr has redirected you too many times.
Do you know why?

https://cdp.bldigitalagency.fr/mautic-whitelabeler/

Thanks

**Comment by nickian** [comment]
Sorry, I'm not sure I can help without more info. This sounds like a server configuration issue, not a bug in the whitelabeler.

Can you post the recent entries to your web server error log?

**Comment by louridi-brahim** [comment]
my htaccess was misconfigured
Thanks
