### ISSUE TITLE
Mautic installation folder not found - Mautic v2.12.1

### ISSUE THREAD

**Issue by kamalsky** [nickian/mautic-whitelabeler#18]
Hi Nickian,

The labeler is great tool, and it works great with 2.12.0. Is it compatible with the newer 2.12.1 version? 

I just upgraded Mautic and the labeler isn't able to find the installation folder. Mautic Root URL works fine. 

Root: /var/www/mautic/
Mautic 2.12.1
Apache 2.4
PHP 7.0
Ubuntu 16.04

**Comment by nickian** [comment]
Thanks. It should be updated now.

**Comment by kamalsky** [comment]
Works great. Thank you!
