### ISSUE TITLE
Save settings for new version

### ISSUE THREAD

**Issue by digitall-it** [nickian/mautic-whitelabeler#19]
For the sake of fast applying and automating the changes on each new version of Mautic:

- save the configuration in a unversioned json file
- save the three images (sidebar, login and favicon logos) in an unversioned folder
- lock the whitelabeler so that if there's a json config file, it will not run from a browser
- allow the whitelabeler to be run from PHP CLI if there are all the needed files

**Comment by nickian** [comment]
I like these ideas! I've been wanting to do something similar with PHP CLI. I'll update soon! Thanks.

**Comment by dev-love** [comment]
Like it as well! +1 for this

**Comment by dev-love** [comment]
Best option would be to have an invisible Mautic mixin (plugin) that auto whitelabels after a new update. To access config, you could define a specific URL that can be accessed only by logged in admins by manually typing it into the address bar of their browser.

**Comment by nickian** [comment]
Sorry I have not been able to get to this yet, other projects have come up. But I love the idea! I'm not yet familiar with how Mautic Plugins work, but I agree that would be great to have it more integrated like that.

**Comment by nickian** [comment]
This exists now in 2.0!
