### ISSUE TITLE
Mautic version 2.7 stuck at Updating CSS colors

### ISSUE THREAD

**Issue by Shishant** [nickian/mautic-whitelabeler#2]
Hi, My mautic-whitelabeler is stuck at Updating CSS colors... 

Please note: Both requirements of gd & allow_url_fopen are enabled.

**Comment by nickian** [comment]
Do you see any errors in the browser console or in your apache log? (`tail -f /var/log/apache2/error.log`).

**Comment by Shishant** [comment]
[Fri Mar 10 09:56:42.653451 2017] [proxy_fcgi:error] [pid 14866:tid 140005984818                                                                                        
944] [client 122.176.45.76:29539] AH01071: Got error 'PHP message: PHP Notice:                                                                                          
Trying to get property of non-object in /opt/bitnami/apps/mautic/htdocs/whitelab                                                                                        
el/index.php on line 46\n', referer: https://mydomain.com/whitelabel/index.p                                                                                        
hp

**Comment by nickian** [comment]
OK. Do you have a package.json file in your root directory? If so, does it look like this one?
https://github.com/mautic/mautic/blob/staging/package.json

The script is failing here for some reason. It's not finding the object that it creates from the json file.

```
$url = json_decode(file_get_contents(urldecode($url).'/package.json'));
if ($url->name == 'mautic') {
    echo 1;
}
```

**Comment by Shishant** [comment]
Yes, its there and it looks exactly the same
![image](https://cloud.githubusercontent.com/assets/17476161/23804539/4fac2a92-05e0-11e7-9afa-631dd8a4c87a.png)

**Comment by nickian** [comment]
@Shishant does it have the correct permissions and is it accessible by your web server? (e.g., `chown -R www-data:www-data your_mautic_folder`

**Comment by nickian** [comment]
It might be easier to save this as a php file and try to run it to diagnose this:

```
<?php
$url = 'http://your-mautic.com';
$url = json_decode(file_get_contents(urldecode($url).'/package.json'));
if ($url->name == 'mautic') {
    echo 1;
}
```

**Comment by Shishant** [comment]
Hi Nickian, 

I tried the following:
`$url = 'https://mydomain.com'; ` 
This removed the error from error_log but still it didnt worked.

So  at the very top I also tried defining:
`$_GET['url'] = 'https://mydomain.com'; `
`$_GET['path'] = '/opt/bitnami/apps/mautic/htdocs';`
Even with this it didnt worked.

**Comment by nickian** [comment]
Did you save what I have above as a separate PHP file and try to run it? What was the output? Did it output "1", or were there any errors, or just a blank page?

**Comment by pckladivo** [comment]
Hi,

I am on a similar issue. I have run the php snip above and i get "1" whitch i guess is expected status.

But when i check the logs in see a strange error:
[Tue Mar 14 10:44:30 2017] [error] [client x.x.x.x] File does not exist: /var/www/html/halmar/mautic-whitelabeler/css, referer: http://mautic.local/halmar/mautic-whitelabeler/

And in the GUI it is stuck on:
Waiting for input ...
> OK
> Looking for compatible Mautic installation ...
> FOUND
> Updating CSS colors ...


kr,
Milos

**Comment by nickian** [comment]
@pckladivo sounds like maybe an htaccess/mod_rewrite issue.

What happens if you try to load this?: 

http://mautic.local/halmar/mautic-whitelabeler/version?path=/your/path/to/mautic

If it's working correctly, it will display your version number.

**Comment by pckladivo** [comment]
If i try your link i get a 404 (http://mautic.local/halmar/mautic-whitelabeler/version?path=/var/www/html/halmar/):
"The requested URL /halmar/mautic-whitelabeler/version was not found on this server."

In apache i have (so that .htaccess it used):
>     <Directory /var/www/html/halmar>
>            Options FollowSymLinks MultiViews
>            AllowOverride All
>            Order allow,deny
>            allow from all
>     </Directory>


kr,
Milos

**Comment by nickian** [comment]
@pckladivo Try doing a git pull to update the repository and run the whitelabeler again. I modified the code to help try to get around this issue (and made it compatible with 2.7.1).

**Comment by pckladivo** [comment]
@nickian The update solved the issue. Thank you for a fast response.

kr,
Milos
