### ISSUE TITLE
Mautic installation not found at this URL. v2.12.1

### ISSUE THREAD

**Issue by jaulaobligatoria** [nickian/mautic-whitelabeler#20]
Hi nickian!!

First of all thank you very much for your work. I've been trying to install it for several days but I always get the same error. I have tried everything that appears in the forum.

I work with apache and I have access to LICENSE.TXT and app / version.tx

Some help?

Thank you very much!

**Comment by nickian** [comment]
Hi @jaulaobligatoria,

Does your host have `allow_url_fopen` enabled? You can create a php file with this in it `<?php phpinfo(); ?>` and search for `allow_url_fopen` on the page to find out.

Make sure the permissions are set correctly for your Mautic files and the Whitelabeler files. Usually setting the owner to www-data is all you need (Set a folder's permissions recursively with `chown -R www-data:www-data folder_name`)

If you're still having issues, look at your Apache error log (usually in `/var/log/apache2/error.log`) and see what the latest messages are at the end of the file after you try to run the Whitelabeler. If you're seeing something like this:

`PHP Warning:  get_headers(http//yoururl.com/mautic/LICENSE.txt): failed to open stream: Connection refused in /public_html/mautic/whitelabeler/index.php on line 44`

Then it's probably a network issue with your host. Ask them about `allow_url_fopen` and doing requests to your own server.

**Comment by jaulaobligatoria** [comment]
Hi  nickian, 

Thanks for your help. Finally allow_url_fopen works!!! 

Thanks!

**Comment by Lutishoski** [comment]
Hi Nickian

I have the same issue with the version 2.12.2.

I have checked the `allow_url_fopen` on.
The permission should also be correct.

Is there maybe a problem with https?

Best regards

**Comment by nickian** [comment]
@Lutishoski it could be related to SSL. Make sure your site doesn't come across any major errors here: https://www.ssllabs.com/ssltest
