### ISSUE TITLE
Test support for 2.12.2

### ISSUE THREAD

**Issue by digitall-it** [nickian/mautic-whitelabeler#21]
v2.12.2 has been released. Will it blend?

**Comment by MapleSage** [comment]
I tried it but it not working or maybe I am doing something wrong.

**Comment by nickian** [comment]
Do a git pull and try again with the new code. I just updated it.

**Comment by MapleSage** [comment]
Hi Nick,

Thanks for the update, I was able to update the logo however the background colors are still not changing  in bitnami aws mautic, it worked fine with mautic.org. However due to other issues with mautic.org install I am switching back to bitnami image, please help. thanks 

Regards

**Comment by nickian** [comment]
Hmm, I'm not sure about bitnami. I'm not familiar with it. Maybe it is a permissions issue? Does the webserver user have access to all of the files?

**Comment by MapleSage** [comment]
It worked in the earlier version so my assumption is that we have access to all files. Let me try changing files manually.

**Comment by nickian** [comment]
Did you update the whitelabeler files with git pull?

**Comment by MapleSage** [comment]
i downloaded the latest version and installed.

**Comment by nickian** [comment]
I'm not sure. Do you have any messages in your apache/server error log?
