### ISSUE TITLE
Mautic installation not found here.

### ISSUE THREAD

**Issue by anythingpixel** [nickian/mautic-whitelabeler#26]
What are some immediate check that can be made when getting the error "Mautic installation not found here."

**Comment by imrodmartin** [comment]
There’s no need to start a new issue... Always best to check the closed ones... 
here’s the instructions:  https://github.com/nickian/mautic-whitelabeler/issues/25

Hope that helps!

**Comment by anythingpixel** [comment]
Ah ok. Got it. Thanks.

———

ROMANE VERNET
Owner / Digital Marketer
(b) 404.624.6842
(c) 678.361.8690

[http://www.anythingpixel.com/wp-content/uploads/2017/10/2color-logo.png]<http://www.anythingpixel.com/>
Web Sites | SEO | SEM | Email Marketing & more.

Let’s Connect:
Facebook<https://www.facebook.com/AnythingPixel/>  |  LinkedIn<https://www.linkedin.com/company/AnythingPixel/>  |  Twitter<https://twitter.com/anything_pixel>  | Instagram<https://www.instagram.com/anything_pixel/>  | Google+<http://plus.google.com/+AnythingPixel>


On May 24, 2018 at 10:34:51 AM, imrodmartin (notifications@github.com<mailto:notifications@github.com>) wrote:

There’s no need to start a new issue... Always best to check the closed ones...
here’s the instructions: #25<https://github.com/nickian/mautic-whitelabeler/issues/25>

Hope that helps!
