### ISSUE TITLE
No logos

### ISSUE THREAD

**Issue by FerRubioMorales** [nickian/mautic-whitelabeler#3]
Hi, i'm using version 2.8.2 and logos are not being uploaded correctly, i ran the process few times and logos are not working, also colors.

**Comment by nickian** [comment]
Did you check everything in the common issues section of the readme file? (https://github.com/nickian/mautic-whitelabeler#common-issues)

Can you tell me what your Apache error log is telling you, and if you have any messages in your browser console?

**Comment by jgitau** [comment]
I also seem to get stuck at loading logos and favicons.,..it just gets stuck there ...rechecking my php and other permissions even as i post this

> Waiting for input ...

> OK

> Looking for compatible Mautic installation ...

> FOUND

> Updating CSS colors ...

> SUCCESS

> Updating company name ...

> SUCCESS

> Updating logos and favicon ...

**Comment by jgitau** [comment]
I also have the following on the log files:
[Sat Jul 15 20:13:07.671639 2017] [:error] [pid 3531] [client 197.232.23.109:51875] PHP Fatal error:  Uncaught Error: Call to undefined function imagecreatefrompng() in /var/www/html/marketing/mautic-whitelabeler/whitelabeler.php:129\nStack trace:\n#0 /var/www/html/marketing/mautic-whitelabeler/whitelabeler.php(177): Whitelabeler->imageResize(192, '/tmp/phpssOWzq', '/var/www/html/m...')\n#1 /var/www/html/marketing/mautic-whitelabeler/index.php(120): Whitelabeler->replaceImages('/var/www/html/m...', 'http://marketin...', '2.8.2', Array, '130', Array, Array, '150', Array, Array)\n#2 {main}\n  thrown in /var/www/html/marketing/mautic-whitelabeler/whitelabeler.php on line 129, referer: http://marketing.brandfi.co.ke/mautic-whitelabeler/

**Comment by jgitau** [comment]
okay fixed my issue....
I was missing php7.0-gd
