### ISSUE TITLE
Does it work with nginx?

### ISSUE THREAD

**Issue by faizanrbhat** [nickian/mautic-whitelabeler#30]
Sorry for raising this as an issue but I don't know how else to comment

**Comment by nickian** [comment]
It should work with nginx. I tested it once and it worked a while back, but I don't regularly use nginx and am not an expert with it. I would test it or back up your files before doing anything on a production server.

**Comment by luisgennari** [comment]
Hello,
i am using Nginx and can't pass through the error: Mautic installation not found at this URL.
How to solve that problem?

**Comment by valione** [comment]
Hello,
I am using Nginx and can't pass through the error: Mautic installation not found at this URL.
How to solve that problem?

**Comment by nickian** [comment]
@valione  We need more information than that to know. What version of nginx, PHP, and Mautic are you using? What do your error logs say? Does your browser console say anything?

**Comment by valione** [comment]
Digital Ocean, PHP 7.0
<img width="527" alt="captura de tela 2018-12-17 as 00 45 40" src="https://user-images.githubusercontent.com/12074424/50063841-40c64000-0195-11e9-9e91-efdf96e76bb9.png">

**Comment by nickian** [comment]
What does the nginx error log say? (Probaby /var/log/nginx/error.log)

**Comment by valione** [comment]
2018/12/22 21:12:47 [error] 32523#32523: *178899 access forbidden by rule, client: XXX.XXX.XXX, server: xxxxxxxx.com, request: "GET /var/log/nginx/error.log HTTP/2.0", host: "xxxxxxxxx.com"

**Comment by valione** [comment]
Help me! Please...

**Comment by nickian** [comment]
Access forbidden sounds like a permissions issue. Maybe your Mautic files are not writable by the server. Can you make sure your Mautic files are owned by the same user as nginx (e.g. "chmod -R www-data:www-data muautic_dir").

**Comment by valione** [comment]
Tks
