### ISSUE TITLE
Mautic installation not found here.

### ISSUE THREAD

**Issue by suportgc** [nickian/mautic-whitelabeler#32]
Hello good afternoon.

I tried everything already and I can not solve it

Can you help me ?

**Comment by tcanani** [comment]
Same here, after updating Mautic, the Whitelabeler couldn't find the absolute path. All permissions are set correctly.

**Comment by nickian** [comment]
This does not support 2.14.1 yet. Please make sure to read the requirements to see the compatible versions. I will update it as soon as possible for 2.14.1.

**Comment by nickian** [comment]
This should work now for 2.14.1. Thanks.

**Comment by pranjal2892** [comment]
does not support 2.15.0??

**Comment by nickian** [comment]
Yes, @pranjal2892 it does work with 2.15.0.

**Comment by pranjal2892** [comment]
I have everything in my mautic rot directory..
Path to my  mautic is /var/www/html/mautic.
It contains package.json, LICENCE.txt
And my Version.txt is in app directory containing text 2.15.0-dev.
still when I run mautic on localhost as well as my server. Every time a message flashes "Mautic installation not found here." and "Mautic installation not found at this URL"
Please Help !!

**Comment by nickian** [comment]
It does not officially support development versions. You can try replacing "2.15.0-dev" with "2.15.0" and running it. I would backup your files first.

If this doesn't work, look at the error log for Apache and see what the errors are saying there.

**Comment by pranjal2892** [comment]
Thankyou for reply @nickian .
I am running nginx.

**Comment by pranjal2892** [comment]
019/03/20 14:34:12 [error] 851#851: *1018 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 1 in /var/www/html/mautic/mautic-whitelabeler/index.php on line 57" while reading response header from upstream, client: ::1, server: localhost, request: "GET /mautic-whitelabeler/index.php?q=url&url= HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "localhost", referrer: "http://localhost/mautic-whitelabeler/index.php"

This is the error nginx showing!!

**Comment by nickian** [comment]
I'm not sure why it's saying this is the request: `GET /mautic-whitelabeler/index.php?q=url&url= HTTP/1.1` 

The &url= should be the URL to your Mautic files. Do you have the cURL PHP extension installed?

**Comment by pranjal2892** [comment]
Yes, it is installed !!

**Comment by nickian** [comment]
Ok, what if you try just putting this code in a PHP file somewhere on the same server and running it in your browser. What do you get?

```
$url = 'http://my-mautic-url.com';

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$curl = curl_init();
curl_setopt_array($curl, array(
    CURLOPT_URL => $url.'/LICENSE.txt',
    CURLOPT_HEADER => true,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_NOBODY => true,
));

echo '<pre>';
print_r(curl_exec($curl));
echo '</pre>';
curl_close($curl);
```

**Comment by pranjal2892** [comment]
i get nothing @nickian
