### ISSUE TITLE
Version 2.14.2

### ISSUE THREAD

**Issue by online-expert** [nickian/mautic-whitelabeler#34]
I have been able to update by changing the app/version.txt file to read 2.14.1 - running white labeler, then changing it back to 2.14.2. In the Mautic Colors dashboard there is a typo 'P**r**imary'. Thanks for this great project nickian!

**Comment by nickian** [comment]
I have updated it for 2.14.2. I don't recommend modifying the version text file unless you run the `compare.php` file. Download the release files for the last version the whitelabeler supports, then download the release files for the new version. Change the `$v1_path` and `$v2_path` variables to your path to the two versions in `compare.php`. Run the script and you will get something like this (this is comparing 2.14.1 vs 2.14.2):

```
Array
(
    [/app/bundles/CoreBundle/Views/Default/base.html.php] => Different
    [/app/bundles/CoreBundle/Views/Default/head.html.php] => Different
    [/app/bundles/CoreBundle/Views/LeftPanel/index.html.php] => Different
    [/app/bundles/UserBundle/Views/Security/base.html.php] => Different
    [/app/bundles/CoreBundle/Assets/css/app.css] => Different
    [/app/bundles/CoreBundle/Assets/css/libraries/libraries.css] => Different
    [/app/bundles/CoreBundle/Assets/js/1.core.js] => Same
    [/app/bundles/CoreBundle/Assets/js/1a.content.js] => Different
)
```

You can see that the Mautic developers have changed something in 1a.content.js. If you ignore this and change the version text file to the latest version the whitelabeler supports, you will be replacing the `1a.content.js` file from version 2.14.1 into your 2.14.2 installation, and who knows what that could possibly break.

**Comment by online-expert** [comment]
Thanks a lot nickian!
