### ISSUE TITLE
don´t work for me

### ISSUE THREAD

**Issue by holatause** [nickian/mautic-whitelabeler#36]

**Comment by holatause** [comment]
<img width="1309" alt="captura de pantalla 2018-11-06 a la s 3 35 55 p m" src="https://user-images.githubusercontent.com/44783321/48092140-d6a39e00-e1d9-11e8-9556-5dce98f4fdb8.png">
Que estoy haciendo mal? al parecer no me reconoce la ruta.

**Comment by nickian** [comment]
Sorry, my Spanish is not good.

Can you provide more information? What does the browser console say? Any errors? Are you using an Apache server? Are there any errors in your error log?

**Comment by lsobral** [comment]
Usted debe colocar el Whitelabeler en la raíz de la instalación del Mautic y precargar los campos más o menos como la imagen que posteé. 
![captura de tela 2018-11-07 as 08 57 50](https://user-images.githubusercontent.com/1202326/48127803-c50ad680-e26b-11e8-9120-84eca8365efe.png)

**Comment by holatause** [comment]
Hello,

I installed the code on my server, where I have mautic mounted but it does not work, you can access it at m.tause.co/master/index.php I do not know how to verify that all the requirements are fine.

you can help?

I installed it via ftp, since mautic I installed it with a third agius.cloud

Stay tuned. ---- On mar, 06 nov 2018 21:54:57 -0500 Nick Thompson <notifications@github.com> wrote ---- Sorry, my Spanish is not good. Can you provide more information? What does the browser console say? Any errors? Are you using an Apache server? Are there any errors in your error log? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by holatause** [comment]
> Usted debe colocar el Whitelabeler en la raíz de la instalación del Mautic y precargar los campos más o menos como la imagen que posteé.
> ![captura de tela 2018-11-07 as 08 57 50](https://user-images.githubusercontent.com/1202326/48127803-c50ad680-e26b-11e8-9120-84eca8365efe.png)

Como los precargo?? yo instalé la carpeta de whitelabeler en la raiz donde esta amutic pero no esta tomando los colores ni nada.

**Comment by nickian** [comment]
This error comes up in the Chrome console when I go to your instance of the Whitelabeler:

`Refused to execute script from ... because its MIME type ('application/octet-stream') is not executable, and strict MIME type checking is enabled.`

in Safari, it says this:

`Refused to execute ... script because "X-Content-Type: nosniff" was given and its Content-Type is not a script MIME type.`

What server are you using? Can you post the virtual host configuration for your Mautic site? Can you try removing the "X-Content-Type: nosniff" from your server's config?

**Comment by nickian** [comment]
It looks like you're using nginx. You'll have to remove this from the config:

`add_header X-Content-Type-Options nosniff;`

The script uses a PHP file to generate the JS file (in order to pass some variables in). I'll see if there is a better way of doing this in a future update.

**Comment by holatause** [comment]
i don´t know how to do this. :(

**Comment by holatause** [comment]
Digitalocean ---- On mié, 07 nov 2018 20:27:39 -0500  Nick Thompson<notifications@github.com> wrote ----Who is your host? I would ask them about this or open a support ticket asking if it's possible to modify the nginx configuration for a site.  —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by nickian** [comment]
You host is Digital Ocean? Ok, so you're just using your own VPS? Did you not install nginx yourself? The config files are probably in `/etc/nginx`

**Comment by holatause** [comment]
nickian 

I can give you access to my server, because it does not work for me. :(

**Comment by nickian** [comment]
Sure, you can send me an email with info through this contact form and I will respond:

https://nick.do/contact/

**Comment by nickian** [comment]
@holatause Try doing a `git pull` now to update the whitelabeler files. I updated the script to stop using PHP to generate variables in the CSS/JS. This should help with the `X-Content-Type-Options nosniff` issue.

**Comment by valione** [comment]
Hello, I've recently migrated to Digital Ocean with Ngynx server. Do you have any suggestion or alternative for a non apache server?

**Comment by nickian** [comment]
It should work with nginx, as far as I know. I'm not an expert with nginx config. If you are receiving a specific error that is different from this one, please feel free to start a new issue.
