### ISSUE TITLE
Stuck in "renegerating mautic assets..."

### ISSUE THREAD

**Issue by khaoua** [nickian/mautic-whitelabeler#37]
Hi Nick

never had any issues with all versions, but this one keeps whitelabeler at step: renegerating mautic assets..., which is corrupting mautic access as it goes into error page 503, any tips ? fyi I proceed for mautic updates via SSH

![image](https://user-images.githubusercontent.com/25910708/48475758-c4d78180-e7fd-11e8-82e9-adb701f53e72.png)

![image](https://user-images.githubusercontent.com/25910708/48475802-e33d7d00-e7fd-11e8-9bb2-5164fc134df4.png)

**Comment by khaoua** [comment]
one comment, it seems that word replacing "mautic" on copy right is not accepting special characters (for me it is : é) while it was before, maybe something to correct for next release ;-)

**Comment by nickian** [comment]
Oh, interesting. I will test that out and see if there is a way to fix it. Thanks.
