### ISSUE TITLE
Its working for mautic 2.15.0 ?

### ISSUE THREAD

**Issue by Bizcrony** [nickian/mautic-whitelabeler#39]

**Comment by Bizcrony** [comment]
Please upgrade this ... so can use with mautic 2.15.0 

Thanks

**Comment by adammmanka** [comment]
i see in the programming it looks to just be a simple path fix see

`<?php
// Compare a new release of Mautic to see if the files whitelabeling affects have been modified.
require_once('whitelabeler.php');
$whitelabeler = new Whitelabeler;
$v1_path = '../2.14.1';
$v2_path = '../2.14.2';
$compare = $whitelabeler->compareMauticVersions($v1_path, $v2_path);
echo '<pre>';
print_r($compare);
echo '</pre>';`

I think we just need to adjust the support to change the path

**Comment by adammmanka** [comment]
Ok checkout nickian's previous solution here: https://github.com/nickian/mautic-whitelabeler/issues/34

**Comment by adammmanka** [comment]
@nickian i have a commit for this where should i commit the changes

**Comment by nickian** [comment]
This will work with 2.15.0 now.

The compare.php file will just compare the last verison of Mautic that is compatible with the Whitelabeler to the newest version of Mautic that I have not analyzed yet. If the the Mautic team have updated code in those files, then they need to be updated in the whitelabeler's templates folder.

Do not run the whitelabeler on a version that is not supported yet. You are risking overwriting critical files and your installation of Mautic could break.
