### ISSUE TITLE
Mautic install not found at url

### ISSUE THREAD

**Issue by ets987** [nickian/mautic-whitelabeler#42]
Hi and thank you for putting this together. 

As the title states, the whitelabeler is not able to find mautic at my url. Here is my error code:

> PHP Warning:  get_headers(http://clickmy.video/fitbomb/LICENSE.txt): failed to open stream: Connection refused in /home/ets987/public_html/mautic-whitelabeler-master/index.php on line 46, referer: http://clickmy.video/mautic-whitelabeler-master/

I have tried all of the recommended fixes in many of the posts.

-allow_url_fopen is on 
-all files exist and are accessible
-I've tried adding package.json. I can access it via browser
-all A's when tested here: https://www.ssllabs.com/ssltest

What else can I try? What could be the issue?

Thanks again.

**Comment by nickian** [comment]
Try doing a `git pull` in the whitelabeler and running it again. I replaced the get_headers() function with cURL. Maybe that will help. This section of the code is actually looking for the `LICENSE.txt` file in the root of your Mautic installation to verify it's actually the correct domain path. Make sure that file is that and has not been modified.

**Comment by ets987** [comment]
I downloaded the latest version just now and uploaded it fresh...did not work.

**Comment by nickian** [comment]
Hmm, do you have the cURL php extension installed?

What happens when you put this code into a PHP file and try to run it?:

```
$curl = curl_init();
curl_setopt_array($curl, array(
    CURLOPT_URL => 'http://URL-TO-MAUTIC.com/LICENSE.txt',
    CURLOPT_HEADER => true,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_NOBODY => true
));
$headers = curl_exec($curl);
curl_close($curl);
echo $headers;
```

**Comment by ets987** [comment]
Maybe I'm doing it wrong, but it just spits out the code in the file. I've tried running it on my server and localhost with wamp. What kind of response should I expect and could you explain how to run it?

For what it's worth, I do have the cURL php extension enabled.
![image](https://user-images.githubusercontent.com/46253295/50569134-4cd10680-0d2c-11e9-838c-293db596e8d7.png)

**Comment by nickian** [comment]
Not sure what's going on here. If you want to let me access your server I can take a look.

Join my chat server here and I can send you a DM:
https://chat.contacts.live/signup_user_complete/?id=mn5jirj38iyi5psskf6epb8m8r

**Comment by luizeof** [comment]
Same here with 2.15.0
![download](https://user-images.githubusercontent.com/257004/50589766-0801b880-0e6f-11e9-9dbf-6716162fd42c.png)

**Comment by nickian** [comment]
@luizeof this looks like a separate issue. Yours can't find the path. This issue is about the URL. Make sure your permissions are set so the whitelabeler/web server can access your Mautic files. Make sure there is a `version.txt` file in your mautic-folder/app folder.

**Comment by nickian** [comment]
I'm closing this ticket because the issue was a dead end. The main issue was there was an entry in the /etc/hosts file confusing the destination of the cURL requests. There still appear to be other issues with the hosting environment on CentOS Web Panel, which I'm not familiar enough with to resolve.

**Comment by kudafintech** [comment]
Hi Nick I am part of your chat server. Would you be able to access my server and take a look, even as part of paid freelance work?

**Comment by nickian** [comment]
@kudafintech I don't currently have time to do this, but maybe someone else here does. Or you could try finding someone on the Mautic forums: https://forum.mautic.org
