### ISSUE TITLE
Not working on ubuntu server

### ISSUE THREAD

**Issue by Bizcrony** [nickian/mautic-whitelabeler#43]
while using this plugin for branding ,, doing fine .. but not updating the new logo. icon. Fevion, name but it says success , and i am getting below error in mautic logs

mautic.CRITICAL: Exception thrown when handling an exception (InvalidArgumentException: The directory "/var/www/html/app/cache/prod/doctrine/cache/file_system" does not exist and could not be created. at /var/www/html/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php line 85) {"exception":"[object] (InvalidArgumentException(code: 0): The directory \"/var/www/html/app/cache/prod/doctrine/cache/file_system\" does not exist and could not be created. at /var/www/html/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php:85)"

Can you help @nickian

**Comment by nickian** [comment]
@Bizcrony Is that an error that comes up when you pull up Mautic after whitelabeling, or something else? It doesn't look like an issue related to the whitelabeler, unless there is an issue with persmissions with the last step running the console commands.

Can you try logging into the server via SSH and going to the /app folder in Mautic. Then run a couple of commands:

`sudo -u www-data php console cache:clear`

Then:

`sudo -u www-data php console cache:warmup`

**Comment by Bizcrony** [comment]
@nickian thank for your reply .. but i did all check and number of time used this liberary to brand mautic but this time really facing an issue ,, whitelabel page says success .. but nothing has changed in mautic :( why i don't know .. all permission and files all fine ..

**Comment by nickian** [comment]
The whitelabeler does not do anything to the `/app/cache/prod/doctrine/cache/file_system` directory at all. I'm not sure how it is related.

Do you have server-side caching turned on? Try restarting Apache. Make sure you're clearing your browser cache after running the whitelabeler.

**Comment by Bizcrony** [comment]
all i did .. nickain

**Comment by nickian** [comment]
If there are no errors in your Apache log and none of those things worked then I'm not sure. I would post an issue on the actual Mautic GitHub page with that error that you received. Someone else might know what that means.

**Comment by Bizcrony** [comment]
if you like i can records

**Comment by nickian** [comment]
Have you checked that the permissions are set correctly on your Mautic installation? I don't know enough about how the caching system Mautic uses. Try asking someone on the Mautic page.

**Comment by RonPimplebut** [comment]
Same here but I run mautic into a docker container. First I was thinking it was related to my docker volumes persistence but since I saw that this post was writted a day ago and after verified my volumes I am not sure anymore. 

I am new to docker so I dont know how to debug this as well but When I inspect the element(the logo), on the login page, once the white labeling as failed I see this : 

<div class="mautic-logo img-circle mb-md text-center" style="width:{{login_logo_width}}px;">
                            <img src="{{login_logo}}" style="width:{{login_logo_width}}px; margin:{{login_logo_margin_top}}px 0 {{login_logo_margin_bottom}}px 0;">
                        </div>

Notice the img path : {{login_logo}}

Any ideas to fix this ?
Thanks

**Comment by Bizcrony** [comment]
[2019-01-15 12:23:15] event.DEBUG: Notified event "console.command" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure". [] []
[2019-01-15 12:23:21] event.DEBUG: Notified event "console.terminate" to listener "Mautic\CoreBundle\EventListener\ConsoleTerminateListener::onConsoleTerminate". [] []
[2019-01-15 12:23:21] event.DEBUG: Notified event "console.terminate" to listener "Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener::onTerminate". [] []
[2019-01-15 12:23:22] event.DEBUG: Notified event "console.command" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure". [] []
[2019-01-15 12:23:22] event.DEBUG: Notified event "console.terminate" to listener "Mautic\CoreBundle\EventListener\ConsoleTerminateListener::onConsoleTerminate". [] []
[2019-01-15 12:23:22] event.DEBUG: Notified event "console.terminate" to listener "Symfony\Bundle\SwiftmailerBundle\EventListener\EmailSenderListener::onTerminate". [] []

**Comment by virgilwashere** [comment]
I pulled the repo down earlier this afternoon, and ran it on my dev server and it executed cleanly.

Mautic `2.15.0`

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
```

**Comment by virgilwashere** [comment]
@nickian, you're already using `file_get_contents` to slurp in the template, why not use `file_put_contents` to write out the branded file?

  `$left_panel_template = file_get_contents('templates/'.$version.'/app/bundles/CoreBundle/Views/LeftPanel/index.html.php');`

This fopen/fwrite/fclose sequence...
```
  $file = fopen($left_panel, "w");
  fwrite($file, $left_panel_new);
  fclose($file);
```

... becomes:

```
  $bytes_written = file_put_contents( $left_panel, $left_panel_new);
  if( $bytes_written !== strlen( $left_panel_new) )
  {
      // an error occurred writing
  }
```
Which would make it easy to add an error message if write issues occur.
I'm not a PHP guy, but it seemed easier to me.  Feel free to ignore me.

V

**Comment by nickian** [comment]
@Bizcrony these look like errors related to the Mautic command console that runs when clearing the Mautic cache. Maybe because permissions are set incorrectly, or you're running the console as a user without sufficient privileges. I am not sure. Better question for the Mautic team.

**Comment by nickian** [comment]
@virgilwashere Thanks. This is definitely not related to Ubuntu, it's something separate, config specific.

I will take a look at the `file_put_contents` function and test that out. I definitely would like to add better error logging and catching exceptions with this script. Hoping to find some time to improve that soon, as well as creating a command line interface option to make the process faster.
