### ISSUE TITLE
Better message when correct template version does not exist

### ISSUE THREAD

**Issue by pjrobertson** [nickian/mautic-whitelabeler#47]
I've been trying to use mautic-whitelabeler, and I kept getting the error `Mautic installation not found here.`. 

After doing some debugging, I figured that my mautic installation was fine, but the real reason for the problem was that my version of mautic (`2.13.0`) was not included in the `templates` folder for whitelabeler.

I suggest the error message be improved from `Mautic installation not found here` to something along the lines of `Incompatible mautic version XXX. See YYY for list of compatible versions` where YYY links to perhaps the `templates` folder on GitHub. Or perhaps even print out the list of compatible versions to the page.

**Comment by pjrobertson** [comment]
Hi @nickian any reason as to why this was closed? It would be great if you could provide an explanation - to help both myself understand and others finding this thread in the future.

Thanks!

**Comment by nickian** [comment]
@pjrobertson sorry for not explaining. v2.0 will now detect the Mautic version and if it's not supported yet, it will tell you. If you try running it on a dev version, it will notify you that dev versions are not supported either.

**Comment by pjrobertson** [comment]
Great， thanks for the reply! Looking forward to v2.0 :)
