### ISSUE TITLE
Link Color Style for the Growl Notification Pop-up

### ISSUE THREAD

**Issue by BillyHilly** [nickian/mautic-whitelabeler#49]
Your white labeler is very useful!
I'd like to suggest an enhancement. It seems the script updates the Growl Notification pop-up with whatever is set as the Primary Color. But for me, that color is dark, which causes any links in the Growl Notification (`.growl-alert`) text to show as that dark color on the dark notification background making the text nearly invisible. The contrast is non-existent.

I'd like to suggest adding the option to set the Growl Notification link color as well.
Here's a picture to give you an idea.
<img width="813" alt="screen shot 2019-02-05 at 8 47 01 am" src="https://user-images.githubusercontent.com/8473727/52277411-ab3c6680-2922-11e9-8e46-746f2aa04c6d.png">

The Growl Notification appears in the Mautic Editor in the top right of the page anytime you perform an action. The problem here seems to be that the `a` tag style that's written in `/media/css/library.css` is applied to links in the Growl Notification.

I noticed the Growl Notification styles are written in `/media/css/app.css` under `.growl-alert`. But there's nothing there defining link color.

Anyways, hope this makes sense. It'd be very useful to be able to dictate that color specifically via your awesome whitelabeler.

Cheers!

**Comment by nickian** [comment]
Thanks for noticing this! I will incorporate a fix for that this week and post an update here.

**Comment by dirtroof** [comment]
You bet! Thank you! Awesome work!

**Comment by nickian** [comment]
It will now use the sidebar color and link color to style the growl notification in the latest release.
