### ISSUE TITLE
2.15.1 template is missing

### ISSUE THREAD

**Issue by taOsemc** [nickian/mautic-whitelabeler#50]
Hi,

1 - 2.15.1 template is missing so i cannot use whitelabeler.

2 - Also, i've noticed that Whitelabeler does not permit to change the logo used by Mautic when the main menu is collapsed. It's actually using the logo we have chosen for the "not collapsed menu" and hiding it.
![2019-02-07 17 02 58](https://user-images.githubusercontent.com/32459602/52424439-4c314a00-2afa-11e9-8d3e-6d9e4d54ac7c.png)

Do you think I could duplicate 2.15.0 template ?

**Comment by nickian** [comment]
There is no official release for 2.15.1 yet (https://github.com/mautic/mautic/releases). You'll only see official releases supported here.

Thanks for pointing out the collapsed sidebar. I didn't even notice that feature. I'll look into a fix for that.

**Comment by taOsemc** [comment]
Hmm it's weird i got this version by pulling the main repository :(

**Comment by nickian** [comment]
Look at the branch. It's because you're cloning the staging/dev version.

**Comment by taOsemc** [comment]
Exact, thank you. :)

**Comment by virgilwashere** [comment]
> There is no official release for 2.15.1 yet ([mautic/mautic/releases](https://github.com/mautic/mautic/releases)). You'll only see official releases supported here.

2.15.1 is now officially released.

**Comment by nickian** [comment]
Working on this now. New version of the whitelabeler is almost ready. It will include 2.15.1 as well as new features.

**Comment by marketic038** [comment]
We are waiting for a working version update for 2.15.1 :)

**Comment by nickian** [comment]
Sorry it's taking so long. Just doing some final testing. Hoping to push an update later today.

**Comment by nickian** [comment]
Scratch that. Ran across some issues when testing. It will have to wait until Sunday. Stay tuned!

**Comment by online-expert** [comment]
Thanks for all your efforts Nick! Enjoy your weekend Sunday; this can wait till Monday. ;-)

**Comment by julianijere** [comment]
Ummm Nick.. its Monday today :)

**Comment by marketic038** [comment]
:) :) :)

**Comment by nickian** [comment]
Haha, it is. Sorry for the delay. Check out the 2.0 release. Make sure to backup your files before trying for the first time. 2.15.1 is supported and we have new features. Let me know if you hit any snags or find any bugs.
