### ISSUE TITLE
404 Not Found 

### ISSUE THREAD

**Issue by Bizcrony** [nickian/mautic-whitelabeler#51]
I upload this plugin on mautic 2.15.0 and installed all the library that suggested https://github.com/nickian/mautic-whitelabeler but getting issue 

[ http://prntscr.com/n73zio](url)

How i get it resolved ?

Thanks

**Comment by nickian** [comment]
What server are you using? Apache? Seems like it's probably either a mod_rewrite or permissions type of error. What does the server error log say?

**Comment by Bizcrony** [comment]
vultr.com nginx

**Comment by Bizcrony** [comment]
42.106.42.101 - - [04/Apr/2019:02:29:24 +0000] "GET /mautic-whitelabeler-master HTTP/1.1" 404 43207 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"

**Comment by nickian** [comment]
I'm not sure what's going on there. This is an issue with your server config though, not the whitelabeler.

**Comment by Bizcrony** [comment]
how i can fix can you suggest ?

**Comment by nickian** [comment]
I don't use nginx, so I'm not sure. Google it and do trial and error until you find a solution: https://unix.stackexchange.com/questions/307759/nginx-404-not-found-when-trying-to-load-files-in-the-directory

**Comment by virgilwashere** [comment]
> how i can fix can you suggest ?

Request the full path to the index.php:

`http://servername/mautic-whitelabeler-master/index.php`

My Mautic nginx config doesn't like it without `/index.php`
