### ISSUE TITLE
Error applying version 2.15.1

### ISSUE THREAD

**Issue by wosubtil** [nickian/mautic-whitelabeler#52]
Hello!

First congratulations for the tool.

After the update I am not able to apply the stylization performed. Errors occur as you can see in the print below.

I noticed that the error occurs when I send the Logos.

![2019-04-16_14-05](https://user-images.githubusercontent.com/18421824/56230083-e0b3ad80-6051-11e9-90d6-6bd9a5512302.png)

Any guidance on what to do?

**Comment by nickian** [comment]
Thanks. Looks like there is an error on the server when trying to process the images. Can you look at the Apache error log on your server? Try running `tail -f /var/log/apache2/error.log`

**Comment by cofundhub** [comment]
Same here. 

Updating css colors..
Error: undefined

![Capture](https://user-images.githubusercontent.com/12230552/56632850-c9fcf000-6629-11e9-81fd-b28888ac39e9.JPG)

**Comment by nickian** [comment]
This is an error related to uploading the images. Can you provide any information from your Apache error log? What server errors are you getting when trying to run this?

**Comment by cofundhub** [comment]
@nickian Now that I tried it again, it's working perfectly now. Maybe because I cleared the cache this time? The log from the other day was gone, so it remains mystery now...

**Comment by nickian** [comment]
@cofundhub oh ok, good. Yes, could have been an old file in the cache or maybe a server-side cache that cleared.

**Comment by wosubtil** [comment]
I tried again and it also worked perfectly. Sorry for the delay in feedback, but I was on the road! I believe that issue has been resolved.
