### ISSUE TITLE
README.md - sudo command line and nginx conf

### ISSUE THREAD

**Issue by virgilwashere** [nickian/mautic-whitelabeler#55]
> WIP -  I will submit a PR.

## formatting
- [ ] (as config.json) =》 (as `config.json`) 

## `.gitattributes`

Specify linguistic language `php`

## ~~`.gitkeep`~~

- [x] assets
- [x] backups

## `sudo`

 For Ubuntu:

```bash
alias wcli='sudo -Hu www-data php7.2 ./cli.php'
wcli ...
```

> CentOS

> Can anyone confirm `sudo` syntax for CentOS/RedHat?

Installation path and usage for multiple vhosts.

### Install

```bash
wlabel_dir="/var/www/mautic-whitelabeler"
hub clone --progress -o upstream nickian/mautic-whitelabeler "${wlabel_dir}"
```

And updates with: `git pull --rebase`

### Usage

Any file references in `config.json` (or equivalent) are relative to `./mautic-whitelabeler/assets`

#### Shared ./assets dir

`/var/www/mautic-whitelabeler/assets` contains images referenced in `config.json`

#### vhost config

Keep a per vhost config file and reference it at runtime.

`/var/www/vhost/whitelabel.json`

```bash
alias wcli='sudo -Hu www-data php7.2 ./cli.php'
cd /var/www/mautic-whitelabeler
# sudo -Hu www-data cp /var/www/vhost/whitelabel.json /var/www/mautic-whitelabeler/assets/vhost.json
# maybe symlink works - havent tried.
sudo -Hu www-data ln -s ../vhost/whitelabel.json assets/vhost.json
wcli --whitelabel vhost.json
```

If anyone is generating a `client.json` file, this bash function might be useful:

```bash
wacky_escaping() {
  : "${1/%\//}"                 # replace / if matches at end
  printf '%s' "${_//\//\\\/}"   # backslack escape all forward slashes
}
```
used thus:

```console
$ path="/var/www/vhost/mautic/"
$ echo $(wacky_escaping $path)
\/var\/www\/vhost\/mautic
```

#### nginx `vhost.conf`

- [ ] header options (+HEAD)
- [ ] location block

<details>
<summary>nginx virtual host config</summary>

```nginx

add-header options... 

location /mautic-whitelabeler/ {
	alias /var/www/mautic-whitelabeler/
	try-files $uri /mautic-whitelabeler/index.php

	location \.php$ {
		fastcgi socket
		fastcgi index
	}
}
```

</details>

#### PHP FPM `php.ini`

- [ ] `max post file size` (sic)

**Comment by uhlhosting** [comment]
@virgilwashere how is the status of this?
