### ISSUE TITLE
Request: Extended {{footer}} options page template

### ISSUE THREAD

**Issue by virgilwashere** [nickian/mautic-whitelabeler#56]
# Request

- [ ] Add `{{footer}}` and `{{footer_prefix}}` fields for inserting content after `{{company_name}}` on basepage and loginpage.

  - `{{footer_prefix}}` defaults to empty string.

  - `{{footer}}` defaults to empty string.

- [ ] Add fullstop `.` after `{{company_name}}` (in body, not title)

## why?

Including my desired content in `{{company_name}}` field results in ugly page titles.

### basepage
On basepage display as `{{company_name}} {{footer_prefix}} {{footer}}`

### loginpage
On loginpage, display over 2 lines as `{{company_name}} {{footer_prefix}}<p>{{footer}}</p>`

## example usage

- [ ] I would set `{{footer_prefix}}` as `All rights reserved.`

- [ ]  I would set `{{footer}}` to: `Privacy policy  | Support` with HTML links.

I will update with full examples.

**Comment by nickian** [comment]
Ok, I liked this idea and went ahead and added it. Take a look.

**Comment by virgilwashere** [comment]
Features added in Release 2.0.2
