### ISSUE TITLE
Error with Docker Mautic 

### ISSUE THREAD

**Issue by luizeof** [nickian/mautic-whitelabeler#57]
Error with docker-mautic:

_**Address timed out. Make sure it's accessible by your server's network.**_

![download](https://user-images.githubusercontent.com/257004/56893875-8dcaf480-6a5a-11e9-9da9-4ce5979aa014.png)

**Comment by nickian** [comment]
It is basically doing cURL request to itself. I don't know much about about Docker networking, but I would try adding a line to `/etc/hosts` to tell your domain to point to itself and see if that has any effect:

`127.0.0.1    e.luizeof.com.br`

**Comment by RonPimplebut** [comment]
Have you tried to tweak your Mautic installation by deleting the LICENSE.txt ? 
I got the same problemes after deleting the Lisence.txt file that is in the Mautic root folder.
