### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by TonyBogdanov** [nickian/mautic-whitelabeler#60]
Right away after installing the repo and opening Mautic I get `Uncaught SyntaxError: Invalid Unicode escape sequence` which is caused by this in the body:

    <script>
		var mautic_path = 'C:\Dev\projects\mautic';
	</script>

I guess no one thought about backslashes.

**Comment by nickian** [comment]
Thanks for pointing this out. I've never tried running it on Windows. I'll give a shot and see if I can get it to work.

**Comment by nickian** [comment]
I believe this can be fixed by adjusting the line 467 of `view.php`:

`var mautic_path = '<?=realpath(__DIR__ . '/..');?>';`

to

`var mautic_path = '<?=addslashes(realpath(__DIR__ . '/..'));?>';`

Please let me know if that works. I'll plan on adding this on the next update.

**Comment by TonyBogdanov** [comment]
Yes, that seems to fix it (at least this particular issue), I haven't checked for others though, I've switched to Linux.

**Comment by luxuryrealtygroup** [comment]
.powered_wsdesk span
                        {
                            opacity: 0.4;
                            font-size: 10px;
                            color: black;
                        }
                        .powered_wsdesk a
                        {
                            opacity: 0.4;
                            font-size: 10px;
                            color: black !important;
                        }
                    
                    
                     Your request (#424) has been received on September 26, 2019 10:43 pm and is being reviewed by our support staff.                                To add additional comments, reply to this email.                                                                Your Issue:                                Yes, that seems to fix it (at least this particular issue), I haven't checked for others though, I've switched to Linux.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/nickian/mautic-whitelabeler/issues/60#issuecomment-502020866
                                Tags : No Tags                                Regards,                                Support 
                Email is a service from Talega Systems. Powered by WSDesk
