### ISSUE TITLE
Class 'Symfony\\Bundle\\FrameworkBundle\\Console\\Application' not found

### ISSUE THREAD

**Issue by giaidieu** [nickian/mautic-whitelabeler#61]
- My server is CentOS 7, PHP 5.6 and 7.2, MySQL 5
- Mautic 2.15.1

- Running Mautic whitelabeler died at step (check attachment, tested with PHP 5.6 and PHP 7.2 both same result)
![Screenshot_2019-05-21 Mautic Whitelabeler](https://user-images.githubusercontent.com/1645038/58071142-cd05e480-7bc5-11e9-904a-56cbe173fc1e.png)

- In server log i got this error message:
[Tue May 21 12:05:01.326516 2019] [proxy_fcgi:error] [pid 30213] [client 192.168.1.105:55050] AH01071: Got error 'PHP message: PHP Fatal error:  Class 'Symfony\\Bundle\\FrameworkBundle\\Console\\Application' not found in /home2/mautic/public_html/whitelabeler.php on line 581\n', referer: 

===============
Step to reproduce:

1. Upload latest core Mautic 2.15.1 then install normally -> It works, can login as admin
2. Upload mautic-whitelabeler to webroot, it will override some mautic core files there
3. Run the web URL again, it will go to Mautic Whitelabeler
4. Select logo images and edit company name
5. Click on "Whitelabel" button
6. Died

Please help and give instruction how i can install missing symfony packages. Thanks!

**Comment by nickian** [comment]
Hmm, can you provide more details about your hosting environment? Does your host let you run the shell_exec() function?

This is the function that is failing in whitelabeler.php:

```php
	public function runSymfonyCommand($path, $command, array $args) {
	    static $application;
	    require_once $path.'/app/autoload.php';
	    require_once $path.'/app/AppKernel.php';
	    $args = array_merge(
	        ['console', $command],
	        $args
	    );
	    if (null == $application) {
	        $kernel      = new \AppKernel('prod', true);
	        $application = new \Symfony\Bundle\FrameworkBundle\Console\Application($kernel);
	        $application->setAutoExit(false);
	    }
	    $input    = new \Symfony\Component\Console\Input\ArgvInput($args);
	    $output   = new \Symfony\Component\Console\Output\NullOutput();
	    $exitCode = $application->run($input, $output);
	    unset($input, $output);
	    return $exitCode === 0;
	}
```

Can you confirm that these files are actually there ("$path" is the path to the Mautic files)?:

```php
require_once $path.'/app/autoload.php';
require_once $path.'/app/AppKernel.php';
```

**Comment by nickian** [comment]
Are you able to run the Mautic command line console manually from the terminal? `cd` to the `/app` folder in Mautic and run `sudo -u www-data php console`

**Comment by giaidieu** [comment]
Hi Nickian,

Thanks for your reply:

**1. Does your host let you run the shell_exec() function?**

Yes, here is the test http://mautic.thietkewebgiaidieu.com/test.php - I am able to execute that cmd with:
$output = shell_exec('ls -lart');

**2. Can you confirm that these files are actually there ("$path" is the path to the Mautic files)?:**

How do i check? In "Where is Mautic installed?" field i have placed correct path there which is "/home2/mautic/public_html" and got message "Compatible version found (2.15.1)"

**3. Are you able to run the Mautic command line console manually from the terminal? cd to the /app folder in Mautic and run sudo -u www-data php console**

Yes, i can run it in terminal, the result is same. Please check my screenshot.
![mautic](https://user-images.githubusercontent.com/1645038/58244010-f5cfda80-7d7b-11e9-9bf2-f6ffec2b7d23.jpg)

Thansk in advance!

**Comment by nickian** [comment]
Can you try replacing the function in whitelabeler.php on line 571-589 with this: 

```php
	public function runSymfonyCommand($path, $command, array $args) {
	    require_once $path.'/app/autoload.php';
	    require_once $path.'/app/AppKernel.php';
	    $args = array_merge(
	        ['console', $command],
	        $args
	    );
	    $kernel      = new \AppKernel('prod', true);
	    $application = new \Symfony\Bundle\FrameworkBundle\Console\Application($kernel);
	    $application->setAutoExit(false);
	    $input    = new \Symfony\Component\Console\Input\ArgvInput($args);
	    $output   = new \Symfony\Component\Console\Output\NullOutput();
	    $exitCode = $application->run($input, $output);
	    unset($input, $output);
	    return $exitCode === 0;
	}
```

Can you go into `/home2/mautic/public_html/app/` and make sure the autoload.php and AppKernel.php files are accessible by the web server user? Shot in the dark, but maybe it's a permisisons issue.

**Comment by giaidieu** [comment]
Hi Nickian,

I have replaced your code to the function but seems no different; please see my screenshot below:

![mautic_code](https://user-images.githubusercontent.com/1645038/58302094-7261c800-7e13-11e9-85e5-8ac84f41773b.jpg)

After replacing code, i tried both on URL http://mautic.thietkewebgiaidieu.com/ and also in terminal but it gives same result:

![mautic_ssh](https://user-images.githubusercontent.com/1645038/58302109-8c9ba600-7e13-11e9-9262-ee3fe6fe7eaf.jpg)

**Can you go into /home2/mautic/public_html/app/ and make sure the autoload.php and AppKernel.php files are accessible by the web server user? Shot in the dark, but maybe it's a permisisons issue.**

I'm using php-fpm so all files in web folder are under user mautic / group mautic as you can see in the screenshot, i think permission shouldn't be the issue.

Thank you!

**Comment by nickian** [comment]
If you can't run the Mautic console from the command line, this is an issue with Mautic, not the Whitelabeler.

What is the "mautic" user?  Is that the system user your web server uses, or is that just an account you created? Are you running Apache? If so, can you try:

`sudo chown -R /home2/mautic/public_html www-data:www-data`

Then run:

`sudo -u www-data php /home2/mautic/public_html/app/console`

If this doesn't work, I would recommend posting an issue on the Mautic GitHub page asking about why you aren't able to use their console from the command line.

**Comment by giaidieu** [comment]
Hi Nickian,

"mautic" is linux user; in the web virtual host it has full permission to run read/write and execute script. My host has multiple websites so i have to set user/group for each virtual host.

Ok, i will test the cmd on a clean Mautic and let you know if it is able to execute. But last time, before i uploaded your whitelabel, i can login to mautic dashboard and can send emails already.

Thanks!

**Comment by virgilwashere** [comment]
> and also in the terminal but it gives the same result:
> `sudo -u mautic php console`

In my 🐧 Linux (⭕️Ubuntu) environment, my _console_ command is actually:

`alias console='sudo -H -u www-data php app/console -vvv'`

which I run as `console` from the Mautic top-level directory (`/home2/mautic/public_html` in your case).

The other part is PHP environment.  You are using `php-fpm` with the webserver, but from the command line, you are actually running within `php-cli` environment.


Does `php -v` return the version of PHP you expect?
Note the `(cli)`

<details>
<summary>php version output</summary>

```console
$ php -v
PHP 7.0.33-10+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Aug  7 2019 09:50:44) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-10+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
```

</details>

```console
root@xemchuky:~# cd /home2/mautic/public_html
root@xemchuky:~# console list
root@xemchuky:~# console mautic:assets:generate
```

Good luck.
