### ISSUE TITLE
Support for Mautic 2.15.3

### ISSUE THREAD

**Issue by amz-x** [nickian/mautic-whitelabeler#74]
Mautic 2.15.3 has been released. Support template needed.

https://github.com/mautic/mautic/releases/tag/2.15.3

**Comment by amz-x** [comment]
Results of ```php cli.php --compare --path1=../2.15.2 --path2=../2.15.3``` on master branch.

array(8) {
  '/app/bundles/CoreBundle/Views/Default/base.html.php' =>
  string(4) "Same"
  '/app/bundles/CoreBundle/Views/Default/head.html.php' =>
  string(4) "Same"
  '/app/bundles/CoreBundle/Views/LeftPanel/index.html.php' =>
  string(4) "Same"
  '/app/bundles/UserBundle/Views/Security/base.html.php' =>
  string(4) "Same"
  '/app/bundles/CoreBundle/Assets/css/app.css' =>
  string(4) "Same"
  '/app/bundles/CoreBundle/Assets/css/libraries/libraries.css' =>
  string(4) "Same"
  '/app/bundles/CoreBundle/Assets/js/1.core.js' =>
  string(4) "Same"
  '/app/bundles/CoreBundle/Assets/js/1a.content.js' =>
  string(4) "Same"
}

**Comment by virgilwashere** [comment]
@nickian, 🎢 bump?

**Comment by nickian** [comment]
Thanks. I will get to this today.

**Comment by nickian** [comment]
It's updated now. Sorry I didn't see or use the PR. There were no changes to the core files the whitelabeler affects, so I just needed to duplicate the 2.15.2 directory, call it 2.15.3, and update the readme file.
