### ISSUE TITLE
Logo & Login Image not showing up

### ISSUE THREAD

**Issue by azedgetech** [nickian/mautic-whitelabeler#77]
Hey, great job on the platform - love the simplicity of configuring things.

Question, though - my favicon is showing up fine, but the logo and the login image are not showing up. All I have is the image representation showing up. I'm running SSL and have verified that the site url in whitelabeler is showing https, as well as config.json. All of the images are showing up in the Assets folder. It is not a cache issue, as I have tried from a different browser that I have not used to access the site with previously and experienced the same thing.

**Comment by nickian** [comment]
So, the images are being uploaded, but will not display in the browser? The only thing I can think of is maybe a permissions issue. Can you check the permissions and owner of your images in assets and make sure they are accessible to your web server?

**Comment by azedgetech** [comment]
That's what I thought initially as well, and I did already check that, but if that were the case, the favicon would not show up.

**Comment by azedgetech** [comment]
All perms on the files are 644, btw.

**Comment by azedgetech** [comment]
The url is https://clikz.us/ausa/s/login if that helps.

**Comment by nickian** [comment]
It's giving a 404 for the image. What does your Apache configuration look like for this site?

**Comment by azedgetech** [comment]
Okay, I found the issue. In the URL (in White-Labeler), it did not have the sub-folder designation. Now the logos are showing up as expected!

**Comment by nickian** [comment]
Oh ok, good!
