### ISSUE TITLE
Support for Mautic 2.16

### ISSUE THREAD

**Issue by dgiebe** [nickian/mautic-whitelabeler#79]
Hello,

I've tried to use it for my Mautic version, but it's not supported. Are there plans to support 2.16.0 too? 

Thank you in advance.

**Comment by nickian** [comment]
I don't see that 2.16.0 exists. The last release is 2.15.3 and it looks like they will announce 3.0 next: https://github.com/mautic/mautic/releases

**Comment by nickian** [comment]
Also, I did not tag a release for 2.15.3. But if you clone the repository instead of downloading a release, it will work with 2.15.3.

**Comment by nickian** [comment]
Looks like there will be a 2.16.0 release. I will update the whitelabeler once this version is out of beta and tag a new release.

**Comment by rodsouto** [comment]
Hi @nickian! 2.16 was released https://github.com/mautic/mautic/releases/tag/2.16.0 , can we re-open this issue? :)

**Comment by nickian** [comment]
Yes, no problem. Working on the update right now. I'll push and tag the release soon.

**Comment by nickian** [comment]
Should be working with 2.16.0 now. Try it out.
