### ISSUE TITLE
ERROR: Could not update images. See console for errors. as below

### ISSUE THREAD

**Issue by Bizcrony** [nickian/mautic-whitelabeler#80]
<br />
<b>Fatal error</b>: Uncaught Error: Call to undefined function exif_imagetype() in /home/campusnom1cs/public_html/m/mautic-whitelabeler-master/whitelabeler.php:496
Stack trace:
#0 /home/campusnom1cs/public_html/m/mautic-whitelabeler-master/index.php(364): Whitelabeler-&gt;replaceImages('/home/campusnom...', 'https://campusn...', '2.15.3', '/tmp/php0oTHK5', '130', Array, '/tmp/phpcWIrQS', '150', Array, '/tmp/phpup9fdG')
#1 {main}
thrown in <b>/home/campusnom1cs/public_html/m/mautic-whitelabeler-master/whitelabeler.php</b> on line <b>496</b><br />

**Comment by Prodigitude** [comment]
Sounds like you need to provision or enable the Exif PHP extension on your server.

**Comment by PapaPingouin** [comment]
Same bug with mautic v3 docker out of the box.
I've made a change on my fork with the function that just check if it was un icon file.
