### ISSUE TITLE
After whitelabeling mautic goes blank

### ISSUE THREAD

**Issue by Proxyseeker2** [nickian/mautic-whitelabeler#81]
Hi,
So after whitelabeling (everything is succesfull) I try to login into mautic again however everything is blank. Just a blank screen with nothing in it. Without whitelabeling mautic works fine but after it I get a blank screen

**Comment by Proxyseeker2** [comment]
Okay so I have no idea why or how but I reinstalled everything a third time and now it worked, for some reason :).

**Comment by nickian** [comment]
I haven't seen that before. Glad it resolved itself. Maybe it had something to do with permissions or caching.
