### ISSUE TITLE
Redirect error

### ISSUE THREAD

**Issue by nitbael** [nickian/mautic-whitelabeler#82]
Hi good day.
I am new at this. Sorry if the question is very basic.
I have a question. I have cloned by url on my server in htdocs.
And I receive this error
------
This page does not work mydomain.com page has redirected you too many times.

ERR_TOO_MANY_REDIRECTS
-----

I have cleared all caches, browser, server. etc

But I think I know what the error is but I don't know how and where to correct it.
Because I see when I enter mydomain.com/mautic-whitelabeler
The browser shows me mydomain.com//mautic-whitelabeler

I should have made the mistake when importing it and I don't know how to eliminate "/"
  left over from the url.

Thanks for the help in advance.

**Comment by nickian** [comment]
Not sure. This sounds like an issue with your web server configuration, not the whitelabeler. Are you using Apache? Are there any errors in your Apache error log file? Can you post the contents of your Apache configuration file?

**Comment by nitbael** [comment]
Hi, 
Hello, thanks for answering. I think I understood the problem.
A bad and duplicate redirect with the server and with cloudflare.

I have removed redirects. The link no longer looks bad.
It looked like this:
mydomain.com//mautic-whitelabeler
Now it looks like this
mydomain.com/mautic-whitelabeler

Although it doesn't work either.
I cleared all caches
https://mydomain.com/mautic-whitelabeler


access_log:188.114.111.110 - - [05/Apr/2020:16:05:44 +0000] "GET //mautic-whitelabeler HTTP/1.1" 301 248
access_log:188.114.111.110 - - [05/Apr/2020:16:05:45 +0000] "GET //mautic-whitelabeler HTTP/1.1" 301 248
access_log:188.114.111.110 - - [05/Apr/2020:16:05:45 +0000] "GET //mautic-whitelabeler HTTP/1.1" 301 248
access_log:188.114.111.110 - - [05/Apr/2020:16:05:46 +0000] "GET //mautic-whitelabeler HTTP/1.1" 301 248
access_log:188.114.111.110 - - [05/Apr/2020:16:05:46 +0000] "GET //mautic-whitelabeler HTTP/1.1" 301 248
access_log:188.114.111.110 - - [05/Apr/2020:16:05:46 +0000] "GET //mautic-whitelabeler HTTP/1.1" 301 248
access_log:188.114.111.110 - - [05/Apr/2020:16:05:47 +0000] "GET //mautic-whitelabeler HTTP/1.1" 301 248
access_log:188.114.111.74 - - [05/Apr/2020:16:18:06 +0000] "GET //mautic-whitelabeler HTTP/1.1" 301 248
access_log:188.114.111.74 - - [05/Apr/2020:16:18:07 +0000] "GET //mautic-whitelabeler HTTP/1.1" 301 248
access_log:81.202.200.184 - - [05/Apr/2020:17:41:07 +0000] "GET //mautic-whitelabeler HTTP/1.1" 302 223
access_log:81.202.200.184 - - [05/Apr/2020:17:41:07 +0000] "GET //mautic-whitelabeler HTTP/1.1" 302 223
access_log:81.202.200.184 - - [05/Apr/2020:17:41:07 +0000] "GET //mautic-whitelabeler HTTP/1.1" 302 223
access_log:81.202.200.184 - - [05/Apr/2020:17:41:08 +0000] "GET //mautic-whitelabeler HTTP/1.1" 302 223
access_log:81.202.200.184 - - [05/Apr/2020:17:41:08 +0000] "GET //mautic-whitelabeler HTTP/1.1" 302 223
access_log:81.202.200.184 - - [05/Apr/2020:17:41:08 +0000] "GET //mautic-whitelabeler HTTP/1.1" 302 223
access_log:81.202.200.184 - - [05/Apr/2020:17:41:09 +0000] "GET //mautic-whitelabeler HTTP/1.1" 302 223
access_log:81.202.200.184 - - [05/Apr/2020:17:41:09 +0000] "GET //mautic-whitelabeler HTTP/1.1" 302 223
access_log:81.202.200.184 - - [05/Apr/2020:17:41:09 +0000] "GET //mautic-whitelabeler HTTP/1.1" 302 223
access_log:81.202.200.184 - - [05/Apr/2020:17:41:09 +0000] "GET //mautic-whitelabeler HTTP/1.1" 302 223
access_log:81.202.200.184 - - [05/Apr/2020:17:41:10 +0000] "GET //mautic-whitelabeler HTTP/1.1" 302 223
access_log:81.202.200.184 - - [05/Apr/2020:17:41:10 +0000] "GET //mautic-whitelabeler HTTP/1.1" 302 223
access_log:81.202.200.184 - - [05/Apr/2020:17:41:10 +0000] "GET //mautic-whitelabeler HTTP/1.1" 302 223
access_log:81.202.200.184 - - [05/Apr/2020:17:41:11 +0000] "GET //mautic-whitelabeler HTTP/1.1" 302 223
access_log:81.202.200.184 - - [05/Apr/2020:17:41:16 +0000] "GET //mautic-whitelabeler HTTP/1.1" 302 223

**Comment by nitbael** [comment]
Although when I cloned the repository, which had not yet done the redirect, I also couldn't start it.

Although in case I have made some errors I have installed Mautic again and I am going to start the cloning of the repository in a new installation.

**Comment by nitbael** [comment]
Hello I have started a new installation, I have cloned the repository.
I do the login and after logged in
I enter mydomain/mautic-whitelabeler
and I get this screen.
https://www.screencast.com/t/HNvcX2waXk

If I enter without login the same thing happens, too.

Thanks for your attention.

**Comment by nickian** [comment]
What does your Apache configuration look like? I'm not sure what's going on without knowing more about your hosting environment. Maybe someone else here might know.

**Comment by nitbael** [comment]
Hi, good morning

I have installed from Bitnami and in google cloud,
Here is a screenshot of the system configuration page.
https://www.screencast.com/t/4SVSmx9hf


Do you want me to show you a specific file?

**Comment by nickian** [comment]
No problem. You could also try just doing the whitelabeling from the command line after manually creating the a .json config file.

**Comment by tobyhutch** [comment]
Hi, I had the same issue (too many redirects error) using Bitnami and AWS. I was able to overcome the issue by adding index.php to the config page URL (mydomain.com/mautic-whitelabeler/index.php). Hope that helps.
