### ISSUE TITLE
Error when changing the title of the login page

### ISSUE THREAD

**Issue by rlucasquaresma** [nickian/mautic-whitelabeler#83]
Hello, 

Running the whitelabel in version 2.16.2, it is not changing the title of the login page, remains in "Mautic" and does not change to what was placed in "Company Name".

Thank you very much for your contribution to the community.

**Comment by nickian** [comment]
Good catch, thanks! I fixed the templates for versions 2.16.1 and 2.16.2 where that wasn't updating the title.
