### ISSUE TITLE
not working and no css on page

### ISSUE THREAD

**Issue by nickwild-999** [nickian/mautic-whitelabeler#84]
Hi, 

This has been working perfectly on a kubernetes deployment, but after some issues with the API I had to delete the pod (which then recreated itself). 

I then deleted app/cache and now when I re-copied the white labeller it no longer works and the page seems to be missing any css and the ability to preview like before.

Can't see how any of this would affect the white-labeler, but I would be grateful of any pointers.

Here is a screenshot:
[https://www.dropbox.com/s/03og4txojhqkycw/Screenshot%202020-04-30%2015.40.40.png?dl=0](url)

Many thanks

**Comment by nickian** [comment]
Hmm, I'm not sure what's going on there. I am not at all familiar with Kubernetes and how it works. It looks like it's not able to find the external CSS/JS scripts it uses. Are there 404 errors in your console?
