### ISSUE TITLE
Mautic URL: Address timed out. Make sure it's accessible by your server's network.

### ISSUE THREAD

**Issue by patodorf** [nickian/mautic-whitelabeler#86]
Hi!

If I'm contacting you is because I've read everything that is here and I haven't found a solution. I have two different Mautic accounts and on my first installation, I have no problem running and enjoying the Mautic-withelabeler. On the second one, I'm having this problem with the Mautic URL.

I've already checked out the following: 

- LECENSE.txt exists and is currently accessible.
- cURL PHP extension is installed
- I have a Valid SSL certificate
- allow_url_fopen= On

What else can I try?

Thanks

**Comment by nickian** [comment]
I'm not sure. Do you have any information from your web server's error log or the browser's console?

**Comment by patodorf** [comment]
Here is what I got, please let me know if this helps!

**From the web server I have this:**

[Mon May 25 19:34:39.627419 2020] [proxy_fcgi:error] [pid 11544] [client 186.158.42.230:46706] AH01071: Got error 'PHP message: PHP Warning:  require(/var/www/vhosts/posta.thepulso.com/httpdocs/app/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php): failed to open stream: No such file or directory in /var/www/vhosts/posta.thepulso.com/httpdocs/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209\nPHP message: PHP Warning:  require(/var/www/vhosts/posta.thepulso.com/httpdocs/app/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php): failed to open stream: No such file or directory in /var/www/vhosts/posta.thepulso.com/httpdocs/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209\nPHP message: PHP Fatal error:  require(): Failed opening required '/var/www/vhosts/posta.thepulso.com/httpdocs/app/cache/prod/doctrine/orm/Proxies/__CG__MauticPluginBundleEntityPlugin.php' (include_path='.:/opt/plesk/php/7.1/share/pear') in /var/www/vhosts/posta.thepulso.com/httpdocs/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php on line 209\n'


**And from the browser's console:**

<img width="530" alt="Captura de Pantalla 2020-05-25 a la(s) 19 41 10" src="https://user-images.githubusercontent.com/41551617/82846735-bb35dc00-9ec0-11ea-808d-97ac8e52bf70.png">
<img width="523" alt="Captura de Pantalla 2020-05-25 a la(s) 19 41 01" src="https://user-images.githubusercontent.com/41551617/82846744-c0932680-9ec0-11ea-953b-50e6849c12be.png">

**Comment by nickian** [comment]
The webserver errors look like messages from Mautic, not the whitelabeler. The problem is that the server is having trouble finding itself by the domain on your network.

Can you open your `/etc/hosts` file? Try adding a line that points your domain to localhost: `127.0.0.1 yourdomain.com`.

Other than this, I'm not sure. This is not a bug with the whitelabeler. It's something with the configuration of the hosting/networking environment. You can try uploading this cURL test into a PHP file on your server and running it. See what the output is:

```php
$url = 'http://my-mautic-url.com';

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$curl = curl_init();
curl_setopt_array($curl, array(
    CURLOPT_URL => $url.'/LICENSE.txt',
    CURLOPT_HEADER => true,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_NOBODY => true,
));

echo '<pre>';
print_r(curl_exec($curl));
echo '</pre>';
curl_close($curl);
```
