### ISSUE TITLE
3.0 support?

### ISSUE THREAD

**Issue by kajahaler712** [nickian/mautic-whitelabeler#87]
Hi, will this also work on 3.0 version?

**Comment by nickian** [comment]
Not yet, but soon. Keep an eye on the releases.

**Comment by nickian** [comment]
Sorry for the delay. This should work now. Let me know if there are any issues. I recommend always backing up your files first before using the whitelabeler in case there is a bug.

**Comment by kajahaler712** [comment]
Thank you.

But it's stuck on "Updating logos and favicon...".

My images are small and I increased upload size in PHP ini.

So no changes are visible (I cleared cache)...

Any idea?

**Comment by nickian** [comment]
This sounds like a permissions issue, maybe. Try making sure the whitelabeler directory is writeable by your webserver. I usually set the owner to Apache: `chown -R www-data:www-data mautic-whitelabeler` or set the permissions to something like `chmod -R 755 mautic-whitelabeler`

**Comment by kajahaler712** [comment]
It already has 755 permissions.

I looked at your documentation again and noticed this line:

allow_url_fopen php.ini directive set to true (file_get_contents function)

I don't have an option to enable this in my cPanel...

**Comment by nickian** [comment]
I'm not sure about that. I would ask your host if that is enabled. Also, check your web server error logs and the browser console for any errors.

**Comment by kajahaler712** [comment]
I have now enabled fopen, but it's still stuck at updating logos and favicon..

The only error in console is this:

login:81 GET https://(mydomain)/%7B%7Blogin_logo%7D%7D 404 (Not Found)

**Comment by nickian** [comment]
The %7B and %7D in the URL are referring to the template brackets {{login_logo}}, so this means PHP was unable to open the template file and replace those template tags with the images you defined.

It looks like it is getting stuck running this piece of code:

```php
$login_page_template = file_get_contents($login_page);
$login_page_new = str_replace(
    // Look for these template tags.
    array('{{login_logo}}', '{{login_logo_width}}', '{{login_logo_margin_top}}', '{{login_logo_margin_bottom}}'),
    // Replace template tags with values.
    array('media/images/login_logo.png', $login_width, $login_margin['top'], $login_margin['bottom']),
    // In this file
    $login_page_template
);
$file = fopen($login_page, "w");
fwrite($file, $login_page_new);
fclose($file);
```

Can you provide the details of your host? What web server? What version of PHP? You could always open a support ticket with your host, show them this snippet, and ask if their installation of PHP supports running this.

**Comment by kajahaler712** [comment]
Will check, thank you
