### ISSUE TITLE
2.16.3 Support

### ISSUE THREAD

**Issue by ShareBtech** [nickian/mautic-whitelabeler#88]
Hi 

Is there any chance of getting a release for 2.16.3 please

**Comment by nickian** [comment]
Yes, this will come with 3.0 support as well. I will try to get this done today.

**Comment by online-expert** [comment]
Awesome, thanks!

**Comment by ShareBtech** [comment]
Hey @nickian 

> Yes, this will come with 3.0 support as well. I will try to get this done today.

Looking forward

**Comment by Robmobius** [comment]
Can't wait for 2.16.3 and 3.0 support. This is exactly what I have been looking. Thank you!

FYI in 2.16.3 (unsupported I know) I get "Couldn't find Mautic. Make sure your path is correct." when pressing the Whitelabel button.

**Comment by nickian** [comment]
Sorry for the delay. Newest release should work with these new versions. Please backup your files before using. I have tested it personally, but it is not thoroughly tested. Let me know if you run across any issues.

**Comment by Robmobius** [comment]
Works for ver 2.16.3 - this my new favourite Mautic plugin/tweak or whatever one would call this. Thanks @nickian - I'll be buying you that coffee. 

About to test on ver 3.0

**Comment by Robmobius** [comment]
I have run into an issue on Version 3. After configuring pressing the white label button I get an "Error: undefined" immediately after the "Updating CSS colour...." in the command prompt window. Screen grab attached. 

![2020-07-11_1610](https://user-images.githubusercontent.com/16938630/87226041-74794400-c391-11ea-8c49-6395d857eea1.png)

**Comment by nickian** [comment]
Thanks. I haven't run across that error before. Do you have any errors in the browser console? Also, anything from your web server error log? What does your hosting configuration look like?

**Comment by Robmobius** [comment]
I see 2 errors in the console

![image](https://user-images.githubusercontent.com/16938630/87241873-932a1a00-c427-11ea-90b0-d7f4418d6bdf.png)

![image](https://user-images.githubusercontent.com/16938630/87241886-a806ad80-c427-11ea-875e-a4ff0203bdac.png)

Nothing in the error log - at least the one that is in the mautic folder in my cPanel - File manager

I am not sure how to describe my hosting. A VPS server using WHM and C panel. Linux and Apache? I am getting out of my death quickly here. The Mautic instance 2.16.3 is on the same server and running fine with white labelled. So logic says the diff is the Mautic Versions?

**Comment by Robmobius** [comment]
Update - seems the issue lay between the keyboard and the chair. If I saved before white labelling it worked.

**Comment by nickian** [comment]
Oh interesting. You shouldn't have to save in order to do the whitelabeling. That should be just a useful side feature to save your settings for future Mautic updates to whitelabel. I'll take another look at this functionality, but glad to hear it is working for you after saving.
