### ISSUE TITLE
Mautic not found: HTTP/2 403

### ISSUE THREAD

**Issue by Almack2013** [nickian/mautic-whitelabeler#89]
Hi @nickian,

First of all, thank you for this tool.
I tried to avoid bothering you with this. But I could not find a solution in the other threads.

I am trying to install the Whitelabeler in Mautic 2.16.0, but I keep getting the message Mautic not found: HTTP/2 403 under Mautic installation address. In previous versions, I managed to get the Whitelabeler working. However, I keep getting this message and can't whitelabel the installation.

I have tried it with different Mautic installs. In sub-domain installations as well as main domain installations.

I really hope you have an idea on how to solve this.

Regards,

Al

**Comment by nickian** [comment]
I'm not sure about that. 403 means "forbidden." Is your Mautic behind some kind of authentication? Maybe check the permissions on Mautic directory. Check your web server for logs. Otherwise, I'm not sure. I don't know if your server being  http/2 vs http/1.1 would be an issue.

**Comment by Almack2013** [comment]
I understand, thanks.
Is there any way I can override the message of the Installation not being there.
Because the install is actually there. 
![image](https://user-images.githubusercontent.com/4168701/87849536-ad616d80-c8e9-11ea-9577-52356206c5c1.png)

Thanks

**Comment by nickian** [comment]
Sure, you could just try opening up `whitelabeler.php`, search for `public function findMauticUrl($url) {` on Line 44. Then on the next line, just paste this:

```php
return array(
    'status' => 1,
    'message' => 'OK, Mautic found.'
);
```

**Comment by Almack2013** [comment]
Thanks, That helped. 
Except after I managed to whitelabel, the login screen seems OK, but after I log in, the next page is a blanc.

Maybe you have an Idea?

Thanks again

**Comment by nickian** [comment]
I'm not sure about that. You'd have to check your web server's error log for any errors to indicate what is going on.

**Comment by Almack2013** [comment]
Hi @nickian,

After upgrading to Mautic 3.01, and using your suggestion of using the additional code to ignore the url to the Mautic installation, I managed to get the Whitelabeler working.

Thanks very much for all your help!

Regards,

Al

**Comment by Almack2013** [comment]
Hi Nick,

Any idea if there is support for Mautic version 3.2.0 in your whitelabeler?

Kind regards,

Al M'charek
al@mcharek.com
06-54915824

**Comment by nickian** [comment]
@Almack2013 No, not yet. 3.2.0 was just released today. I have to look at its code to see if anything needs to be adjusted before adding support to the whitelabeler. I will try to add support for it this week.
