### ISSUE TITLE
New version unable to verify system path

### ISSUE THREAD

**Issue by deepvoice** [nickian/mautic-whitelabeler#9]
Permissions are correct.
Previous version found path correctly.

Where is Mautic installed?
Absolute path to Mautic's root on your server. 
Mautic installation not found here. 

apache2 runs as www-data
All directories owned by www-data

**Comment by nickian** [comment]
Oops. I didn't have the correct templates files added on that last push. Try git pull and try running it again. Thanks.

**Comment by meeerp** [comment]
HI,

How about for nginx with php-fpm?
Please advise how to fix it.

thanks.

**Comment by nickian** [comment]
I'm not sure about nginx. I haven't used it. I would do some Googling about permissions and what user it runs as in your environment.
