### ISSUE TITLE
Feature Request - Auto Updater

### ISSUE THREAD

**Issue by TornMarketing** [nickian/mautic-whitelabeler#92]
Hey mate,

What would it take to build out something that allows the white labeller to auto-update based on the most recent version in Github?

Something along these lines, although this is 7yrs old
https://github.com/yosko/php-github-updater

**Comment by nickian** [comment]
That's an interesting idea. Definitely something I will consider and look into. Thanks.

**Comment by nickian** [comment]
I think this should be a separate script. I don't want to get cron or shell scripts involved inside this repository. You could create a separate script that cron runs to do a git pull, or something like that.
