### ISSUE TITLE
Mandatory directory name

### ISSUE THREAD

**Issue by Vartkat** [nickian/mautic-whitelabeler#94]
I've experienced that : 
Install from ZIP donwloaded from Github, extract zip, zip gives a directory name 
mautic-whitelabeler-master

If you keep this name, it doesn't work, directory name has to be 
mautic-whitelabeler

**Comment by yarimiz** [comment]
@Vartkat the directory name inside the zip always includes the release version. After you uzip, just use the mv command to rename it.
