### ISSUE TITLE
Typo in version prevents updates

### ISSUE THREAD

**Issue by TonyBogdanov** [nickian/mautic-whitelabeler#95]
There's a typo I believe in the name of a tag: `2.05` which probably was supposed to be `2.0.5`, unfortunately this seems to be considered as "newer" than say `2.0.8` and prevents proper updates when using composer.

**Comment by nickian** [comment]
I tried updating the tag. I'm not sure about using composer for this. I always just clone the repository and use "git pull" to update the files. I can look more into this with the next update here.

**Comment by TonyBogdanov** [comment]
No need for any updates, composer does exactly git pull internally after it queries all available tags and picks the one that corresponds to the version you've specified in your project. The problem is the **picking of a version** part since it thinks `2.05` is newer than `2.0.anything`, so it can't pick the proper tag to clone.

In short, just rename the tag to `2.0.5` or delete it (since there already is `2.0.5`) and the issue will be resolved.
