### ISSUE TITLE
Support mautic version 3.1.1

### ISSUE THREAD

**Issue by yarimiz** [nickian/mautic-whitelabeler#96]
Hey,
Is it possible to add support for Mautic v3.1.1?

Thanks!

**Comment by nickian** [comment]
Thanks for the reminder. I will test this tonight.

**Comment by RobMSBand86** [comment]
Any news on this @nickian? Just started using Mautic and your plugin and then upgraded to 3.1.1 :-(

**Comment by GemsFord** [comment]
Please update the script! ❤️

**Comment by willdotcom** [comment]
Hello, any update for 3.11 ?

**Comment by nickian** [comment]
Sorry for the delay. I just tested it with no issues on my end and created a release. Still, I recommend you always make a backup. No guarantees with the whitelabeler!
