### ISSUE TITLE
3.1.1 White-labeling giving "Undefined" error on web front end

### ISSUE THREAD

**Issue by Deepenmak** [nickian/mautic-whitelabeler#97]
It says that CSS files updated with new colors, but somehow they aren't updated. Company name is not replaed.

Below is the Commandline output:

Whitelabeling...
Updating colors...
CSS files updated with new colors!
Updating company name in templates...
Updated company name in templates!
Updating logo files...
PHP Warning:  imagepng(/mautic/htdocs/media/images/sidebar_logo.png): failed to open stream: Permission denied in /mautic/htdocs/mWM_old/whitelabeler.php on line 471
PHP Warning:  imagepng(/mautic/htdocs/media/images/login_logo.png): failed to open stream: Permission denied in /mautic/htdocs/mWM_old/whitelabeler.php on line 471
Logos updated!
Clearing Mautic cache...
PHP Warning:  file_put_contents(/mautic/htdocs/var/cache/prod/appProdDebugProjectContainerDeprecations.log): failed to open stream: Permission denied in /mautic/htdocs/vendor/symfony/http-kernel/Kernel.php on line 648
PHP Warning:  file_put_contents(/mautic/htdocs/var/cache/prod/appProdDebugProjectContainerCompiler.log): failed to open stream: Permission denied in /mautic/htdocs/vendor/symfony/http-kernel/Kernel.php on line 649
Rebuilding Mautic assets...
PHP Warning:  file_put_contents(/mautic/htdocs/var/cache/prod/appProdDebugProjectContainerDeprecations.log): failed to open stream: Permission denied in /mautic/htdocs/vendor/symfony/http-kernel/Kernel.php on line 648
PHP Warning:  file_put_contents(/mautic/htdocs/var/cache/prod/appProdDebugProjectContainerCompiler.log): failed to open stream: Permission denied in /mautic/htdocs/vendor/symfony/http-kernel/Kernel.php on line 649
Finished!
Make sure to clear your browser's cache if your Mautic styles aren't updated after a browser refresh!

---------------
Also tried clearing the serevr cache, still the same problem.

**Comment by nickian** [comment]
"failed to open stream: Permission denied"

This is an issue with file permissions/ownership of the files on your server. Make sure the webserver has read/write access to the Mautic files and the Whitelabeler files.

For example, if your webserver user is `www-data`, give ownership to the server: `chown -R www-data:www-data /var/www/html`
