### ISSUE TITLE
Security Patch means that we need 3.2.4 Support

### ISSUE THREAD

**Issue by Prodigitude** [nickian/mautic-whitelabeler#98]
With Mautic issuing a critical security patch and urging us all to update as soon as possible, we could really use White Labeler support for the 3.2.4 version.

**Comment by Prodigitude** [comment]
I kind of hacked it and it does look compatible. So it would be minimal work for you. Thank you so much for this script.

**Comment by nickian** [comment]
Thanks for the reminder. I see a new release and the security patches. I will create some updates to make them all compatible here shortly.

**Comment by TornMarketing** [comment]
Hey @nickian 
What's the checklist process mate? 
Something we could assist with?

**Comment by nickian** [comment]
Ok, I just pushed support for all of these versions, so they should work now:

* 2.16.4
* 2.16.5
* 3.2.2
* 3.2.3
* 3.2.4

The process looks like this:

1. Look at the last supported version in the `templates` folder
2. Download that version and the next version
3. Use the `compare.php` tool to see if the files affected have changed.
4. Also, compare file changes in the tagged versions in the Mautic repository
5. Copy the template version folder and rename it to the new version
6. Make any changes to the templates if the code has changed in the new version, or just leave as is if the code hasn't changed.
7. Test it out
