### ISSUE TITLE
Mautic not found. Make sure LICENSE.txt exists

### ISSUE THREAD

**Issue by himala76** [nickian/mautic-whitelabeler#99]
Hi Nick,
I'm getting Mautic not found. Make sure LICENSE.txt exists in the domain root, 
all the requirement has been met with server-side and I can see the file set on the root folder 
I'm running Mautic 3.2.5 

Can you give some advice?

Thanks

**Comment by onlineexpert** [comment]
Maybe a read permission issue on the LICENSE.txt file?
Make sure your webserver may read the file as owner or group member.

**Comment by himala76** [comment]
I did bypass this issue by adding
`return array(
    'status' => 1,
    'message' => 'OK, Mautic found.'
);
`

**Comment by nickian** [comment]
I'm not sure why this cURL function doesn't work for some people. But yes, you can bypass by just changing the method to return an array with 1 there for the status.

**Comment by anonymnia** [comment]
> return array( 'status' => 1, 'message' => 'OK, Mautic found.' );

I have the same problem. Where exactly should I put this code? At which folder, file, line?

**Comment by nickian** [comment]
Lines 101-118 in this file: https://github.com/nickian/mautic-whitelabeler/blob/master/whitelabeler.php

Where it says `return` and returns an array. You could just replace the second and third return lines to match the first one: `return array( 'status' => 1, 'message' => 'OK, Mautic found.' ); `

**Comment by kudafintech** [comment]
h now my mautic dashboard is just blank

**Comment by diverso** [comment]
didn't work for me, getting another error when hitting "whitelabel" button

"
> Waiting for input ...

> OK

> Looking for compatible Mautic installation ...

> FOUND

> Updating CSS colors ...

> ERROR: undefined

"
please advise
